#+title: Note Taking with Org Mode
#+author: Ryan Harvey

* Purpose of this document
I need to have a document that is where I need it when I need to refer to it or edit it, however I need.
This document will consist of how I will take notes with org-mode, in either classes or self-study.

* General practice
** Detailed Explanation
I will only take org-mode notes if I need to.
The qualification for "needing" to take org-mode
notes is that my other note-taking methods aren't
"enough" or they're just not even possible.

This isn't to say that org-mode notes are superior
or that my other note-taking methods don't work and
should be tossed. There are uses for all of my methods.

+ *Supernote*
  Writing with the pen for my Supernote is old-fashioned and slow,
  but it is an effective learning strategy for practicing thoughtful
  subjects one of which is math, which also needs a pen because of the
  various symbols and ease of using a pen which is faster than any other
  method.
+ *Sticky notes on books*
  These are useful to me because it is an ease of access and it allows me
  to have notes right by the text I'm getting those quotes from. It will
  allow me to go back to a book and jump straight to a topic that I would
  need. The process of doing this is time-consuming, but the amount of time
  put into it will return a greater amount of knowledge in the long run.
  It's an old-fashioned version of org-mode that has it's uses, such that
  org-mode can't be tangible and as easy to look through as a 3d object
  that time has been put into.
+ *Org-mode*
  Org-mode completes the last two, it has the ability to explain the main
  ideas of anything that I learn. It can be a structured document that
  cuts the whole concept/class into sections that I flesh out individually.

  Org-mode is the best at referring back to because it will lead me to what
  I'm asking for, because it will have the main ideas/summaries of the big
  picture that can be divided into any number of smaller pictures.

  While Supernote and Sticky Notes with books are useful, they are time-consuming
  and they're the "work" part of note-taking. Whereas org-mode, if needed, can
  sum up the main ideas as a whole, then extrapolate each idea on its own, such that
  instead of looking for how to solve a certain problem in my math class by looking
  at examples of problems, I can look at the explanation of the problem perfectly
  with a step by step basis of ideas, that are ultimately summed up that make perfect
  sense. And the collection of all of these ideas aren't just isolated in one spot, like
  how Supernote and Sticky-Notes behave, they can be as interconnected/together as I need
  them, using tags in org-mode and other strategies that org-mode offers me.
** Examples
*** Old testament lineage/story connection
This is a good example of needing org-mode notes because though I
would have notes within my Bible and within other books going over
this lineage, they wouldn't be in a nice readable format that org-
mode provides. 
*** Any sort of reading book
Especially Dostoyevsky books, I read them and I enjoy the psychology, but
after reading them I don't have a way to see my thoughts throughout the book.
Or even a clear, concise way of referring back to how the book was. Org-mode
would help with that.
*** Math classes
One problem with math is how expansive it can get and how concepts can be forgotten
and not even seem to exist just because they have been hiding in the dark after they
were used last. This can either sneak up on finals, or it can just be a detriment to
valuable knowledge that was missed because it wasn't kept track of. It could also
come up in a future class or problem where one needs it but it ran away from the brain
as soon as it went undocumented.

Also it's just nice to see all of the concepts for a particular math field. Summaries
are good and that's what org-mode excels at.
*** CS classes
Org-mode would be beyond beneficial for cs classes. One detriment to note-taking in cs
classes in general is that it is never usually defined in words, it is shown through
example or a professor/textbooks explanation of it. This "problem" gets solved usually
with hard practice toward concepts and problems within that scope of cs and the
particular language. Even after solving the problem this way, it usually just stays in
the mind and is never expounded upon, like how math proofs would be or how essays would
make one ponder and make an original work that shows the inner-workings of their mind.

Org-mode would solve this problem. While working hard at concepts and practicing, once
a clear conclusion is made, instead of just saying it in one's mind or in the space they
are in, they can have a document that stores their thoughts and is able to store summaries
and thoughts on concepts and problems that later down the line would be useful to look back
on. Org-mode would be to general cs concepts as comments are to code. It makes even your
understanding of CS readable, lest you forget a tiny detail and would suffer to search for
that detail or idea in a brute-force fashion.

** Ideas
*** Formatting Ideas
I can include, if a certain topic gets convuluted, a sort of
reference end of the file where I can include common questions
or problems that relate to the topic, and I can refer to the
section in the file that covers that topic or I can answer it
simply and say "refer to ch ?.? for a more concise answer" or
something along the lines of that.
*** Inline Images
These will be of great use to me, whether it's a snippet of code,
a math formula, or an image that represents an idea, it will help me
visualize alongside the words that I use to convey/know the idea.
*** LaTeX
with org-mode, I can have a specific note-taking strategy that can be exported to LaTeX,
or I can just have a normal setup of an org-file but have some ideas able to go into a
seperate LaTeX pdf that I can reference within my org-file, and even snippet certain
pieces of it.
*** Reveal.js
org-reveal is a great way for me to do slideshow presentations and even
have just a clear presentation of a chronological timeline of anything
imaginable. This goes hand in hand with org-files and notes especially.

