
* Ryan Harvey and Fr. Michael Monos - Saint Luke Orthodox Church
:PROPERTIES:
:ETag:     "3419004850294000"
:LOCATION: 1510 Audubon Drive, Columbia, MO 65201
:calendar-id: rharv99@gmail.com
:entry-id: 00nv4ean2kgcn9m34ho10pmcfk/rharv99@gmail.com
:org-gcal-managed: gcal
:END:
:org-gcal:
<2024-03-09 Sat 15:45-16:15>

Event Name: Confession - Orthodox Christians


Location: 1510 Audubon Drive, Columbia, MO 65201

Need to make changes to this event?
Cancel: https://calendly.com/cancellations/5a972641-1075-43b5-b4af-54c06fc57e26
Reschedule: https://calendly.com/reschedulings/5a972641-1075-43b5-b4af-54c06fc57e26
:END:

* Open Discussion
:PROPERTIES:
:ETag:     "3420240539290000"
:LOCATION: https://saintlukecolumbia.webex.com/saintlukecolumbia/j.php?MTID=m9a62f0ecddb52e35e5e10731f657d748
:calendar-id: rharv99@gmail.com
:entry-id: _6hgm4phg70om4b9o6kpj8b9k69gjebb26go3ebb269hj8chhcopjicpi64/rharv99@gmail.com
:org-gcal-managed: gcal
:END:
:org-gcal:
<2024-03-13 Wed 19:00-19:45>

An online discussion for Catechism Class.
-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-





JOIN WEBEX MEETING
https://saintlukecolumbia.webex.com/saintlukecolumbia/j.php?MTID=m9a62f0ecddb52e35e5e10731f657d748
Meeting number (access code): 2667 263 1985

Meeting password: duDpjPtT345 (38375788 from video systems)



TAP TO JOIN FROM A MOBILE DEVICE (ATTENDEES ONLY)
+1-650-479-3208,,26672631985## tel:%2B1-650-479-3208,,*01*26672631985%23%23*01* United States Toll


JOIN BY PHONE
+1-650-479-3208 United States Toll

Global call-in numbers
https://saintlukecolumbia.webex.com/saintlukecolumbia/globalcallin.php?MTID=m58cad29027dde15a94d6a1f21676cdf6


JOIN FROM A VIDEO SYSTEM OR APPLICATION
Dial sip:26672631985@saintlukecolumbia.webex.com
You can also dial 173.243.2.68 and enter your meeting number.





Can't join the meeting?
https://collaborationhelp.cisco.com/article/WBX000029055


IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.
:END:

* Catechism Online Discussion
:PROPERTIES:
:ETag:     "3421893562050000"
:LOCATION: https://saintlukecolumbia.webex.com/saintlukecolumbia/j.php?MTID=m748c81034825b26521b380e631075e4f
:calendar-id: rharv99@gmail.com
:entry-id: _6kr38c9k74o6cbb161h3eb9k6tim8bb165i34bb16hh62pj36hj34d9lc8/rharv99@gmail.com
:org-gcal-managed: gcal
:END:
:org-gcal:
<2024-03-21 Thu 19:00-20:00>

Open discussion. Bring questions.
-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-





JOIN WEBEX MEETING
https://saintlukecolumbia.webex.com/saintlukecolumbia/j.php?MTID=m748c81034825b26521b380e631075e4f
Meeting number (access code): 2663 939 7174

Meeting password: VmrDxKV7M65 (86739587 from video systems)



TAP TO JOIN FROM A MOBILE DEVICE (ATTENDEES ONLY)
+1-650-479-3208,,26639397174## tel:%2B1-650-479-3208,,*01*26639397174%23%23*01* United States Toll


JOIN BY PHONE
+1-650-479-3208 United States Toll

Global call-in numbers
https://saintlukecolumbia.webex.com/saintlukecolumbia/globalcallin.php?MTID=m1b51b2a14036f0d270cae5ed16ae5d41


JOIN FROM A VIDEO SYSTEM OR APPLICATION
Dial sip:26639397174@saintlukecolumbia.webex.com
You can also dial 173.243.2.68 and enter your meeting number.





Can't join the meeting?
https://collaborationhelp.cisco.com/article/WBX000029055


IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.
:END:


