#+title: Safeguard for the Soul
#+author: unknown
#+options: num:nil toc:nil 
* Day 1 
** Concerning the Worth of Salvation
1. My salvation is a matter entirely my own. If I do not have concern for it, who else will?
2. My salvation is a matter concerning my whole soul and body. If I do not make sure of my salvation, who else will make sure of it for me?
3. My salvation is a matter concerning all eternity. If I do not work for it, who else will work for it for me?
   And what do I do? Why don't I care at all for the salvation of my soul? I do not have anything better than this soul. I do not have anything
   worth more than this immortal soul. So, if I lose it just one time, I will have lost the greatest good for all eternity.

   /Offer all of your effort to the Holy Trinity through the Virign and your Guardian Angel, and your patron Saint that you have as a protector,
   so that the effort you put forth may be unto the glory of God and unto the salvation of your soul./

* Day 2
** Concerning the Uncertainty of the Hour of Death
1) The verdict has been made, I must die, but I do not knwo when. I may die this very day, this very hour.
2) And I do not where I will die. I may die either where I sleep, or where I walk, or where I stamd, or any other place I go.
3) And I do not know how I will die. I might die while uncorrected in this or that sin. How is it that I still sin with such
   joy and fearlessness? That I still fall again and again so easily? That I do not flee every cause of sin? What kind of faith do I really have?

   - /Be resolved not to lose any time, for time is a great means for you to live virtuously and to arrange the days' tasks. That hour which you
     lose could very well be the last hour of your life. And that hour which you use well may bring about the eternal salvation of your soul./

* Day 3
** Concering the Awareness of the Time of Death
1) If I do not die a sudden death, I might be informed of the time of my death so that I may amend my ways and have time to confess my sins.
    However, then I will only be able to confess with great difficulty on account of the burden of sickness.
2) Perhaps all my faculties will be working so that I will be able to examine my conscience; but then it will be veryt difficult to be in the
   right state of mind on account of my fear.
3) Perhaps I will have a heart so that I may make a good repentance; but then my conscience will be confused from so many sins. O my God, what shall I do?

   /Always have your soul in good order and remove every thing that disturbs your conscience. You should have a good Spiritual Father. And do not lost the
   time which God has given you so that you may once and for all truly amend your ways./

* Day 4
** Concerning Preparation for Death
1) What must I do so that I die a good death? I must do those good things which I will want to have accomplished before the hour of death arrives
2) I must do those things that I may not be able to do in the hour of death.
3) I must do those things which I absolutely should have done prior to that hour, namely, true repentance for my sin, the exercise of interior contrition, and the courageous fleeing from the causes of every sin.

   /Among the other tasks of today, meditate upon death, repenting for your sins, and making the resolute decision to serve God according to your ability./

* Day 5
** Concerning the Condition of Dying
1) The past sins of a dying man distress him, for he did not repent of them as he should have.
2) His present condition embitters him, for he sees so many dangers and has no way to escape them.
3) The future life frightens him, for, being faced with eternity, he does not know which eternity
   he will enter in to, that of enjoyment, or that of hell. If even the righteous tremble, what
   will I do, the thrice-wretched sinner?

   /Confess this very day if you are certain that you have not confessed some moral sin, or if you are uncertain of having confessed it. And if you feel that you are in the grace of God, thank Him and entreat Him
   to keep you in such a state until the end./

* Day 6
** Concerning the Final Hour of Life
1) In that hour, the soul will seperate from the body and from comforts.
2) In that hour, all honors, riches, and friendships will come to an end.
3) I might be damned at that very moment. If that is the final moment, what will come of me?
   O final moment, from which eternal life dangles!

   /Designate each day for the examination of your conscience, in the evening if you can. And have reverence for your Guardian Angel./

* Day 7
** Concerning the Partial Judgement
1) At the time of my death there will be an inquisition, at which I will see myself lying on my bed being examined.
2) On my left will be the devil, laughing, with a great book opened wide, so I may read all the sins of my life which are clearly written therein.
3) On my right will be standing my Guardian Angel, reading a small book which contains the little good I did in my life, who will, with a sad countenance, present the book before my eyes.
   O what a judgement! O what a sight! O what fear!

   /Ask the Lord to keep you from angering Him further, and that you might receive a good death./

* Day 8
** Concerning the Place of the Soul after Death
1) If the soul is bound for blessedness, being full of virtues, the angels will immediately accompany it with great joy. And what joy it will be!
2) If the soul is bound for hell, being bereft of every virtue, it will immediately be seized by the demons. By which will I be seized, by the angels, or by the demons?
   And to which place will I go?
3) If the soul is condemned to Hades, alas! Who can describe the terribleness of that prison, in which the soul will remain until the Second Coming, when it will receive its full punishment?

   /After examining your conscience this evening, reflect on your life, and determine what place is fitting for you. And before laying down for bed, entreat the Lord to deliver you from eternal punishment./

* Day 9
** Concerning the Condition of the Body after Death
1) Consider what will become of your body after death. It will be pale, without form, dirty, and hideous. It will not be able to see, or talk, or hear. It will be motionless, senseless, without a single ability.
2) Where will your body be brought? To the Church, accompanied by priests, who, after a few prayers, leave it to be buried in the cemetery, to be placed in the dirt, where it will rot and be consumned by worms.
   Is this the body that I flatter and indulge with so many luxuries and pleasures?
3) And what happens after it is buried? It will be erased from the memories and imaginations of men. It will be so forgotten, that it will be as if it had never existed in the world at all.

   /Remember how all the vanity of the world comes to an end. And remember that the body that we caress so much and expend so much effort on will decay completely. Therefore, come to hate bodily comforts, and forsake vanities.

* Day 10
** Concerning the Examination of our Life
1) As long as I am alive and work good and evil, I write these things as if in a book, which book will one day be read. That is, the evil things that I should not have done, but did, will one day be read.
2) The good thins which I could have done, but did not, will be read.
3) Lastly, the final verdict will be given to me. But which verdict? The one I prepare by my works.

   /Take a good look at your life and consider your sins, and how many good things you did not do because of social or other reasons, and hate every evil thing taht you have done, and be determined to live a virtuous life from now on and forevermore./

* Day 11
** Concerning Repentance
1) If I have sinned, I must repent. Is this not how it is? But when will I repent? After death? Impossible, for I will no longer have time.
2) Will I repent in the hour of death? This is the most difficult, for then I will have little time, and I will be weighted down by illnesses and weakness.
3) There is no other time within my power except the present. Therefore, I must immediately repent now, because later I may not be able to repent.

   /Make an effort every evening to repent and ask forgiveness from God for all the evil deeds you have committed, all the evil words you have spoke, and all the evil thoughts you had, and hasten to confess all these things to your Spiritual Father and carry out the prescribed rule for them./

* Day 12
** Concerning the Last Judgement
1) These are all the signs which will come to pass at the future judgment, just as the divine Scriptures say: the sun will become dark; the moon will be covered as if from black blood; the stars will roar; the earth will split into yawning chasms; there will be terrible earthquakes, horrific wars, and many other things.
2) The judgment will come suddenly, when no one is expecting it, when men are sinning, when there will be no more time for them to repent and amend their ways.
3) Fire will rain from heaven with great terror, consuming in its flames man, beast, plant life, countries, cities, and the whole world. O what fiery destruction! If the insensible creations will have such fear on that day, how much more fear will sinners have?

   /You must do three things for this meditation:/
   /1) fear the divine righteousness of God;/
   /2) have contrition over and repent of your sins; and/
   /3) make humble supplication to the divine compassion of God/

* Day 13
** Concerning the Resurrection of the Dead
1) At the fearful sound of the angels' trumpets this body of mine will resurrect from that very place where it lies dead.
2) My soul will be called forth from where it is found in order to reunite with my body.
3) My body, along with my soul, will then be immortal. But which immortality will I inherit? The wretched immortality on
   account of the sins I practiced, or the blessed immortality on account of the repentance I showed and the virtues I did?

   /Practice some sort of fasting and self-control, or some other hardship. And, if you are able, give alms, so that God may grant you true internal/
   /grief of repentance and compunction on account of your sins./

* Day 14
** Concerning the Advent of Christ
1) Jesus Christ will come triumphantly with His Cross, accompanied by myriads of angels, with His most-holy Mother next to Him, surrounded by the Apostles and all the Saints; fearsome, glorious, seated upon the clouds. As my fashioner, He will seek an account from me due to all the graces and means He gave me unto my salvation. But I, the ingrate, used them poorly.
2) And, as a father, He will seek an account from me due to the great love He showed towards me. But I repaid Him so thanklessly.
3) And, as my Savior, He will seek an account from me due to the great amount of blood He shed for me. But I, like a mindless beast, stomped on it so many times.

* Day 15
** Concerning the Revealing of the Conscience at the Future Judgement
1) Not a single one of my many sins will be hidden or kept silent at the Judgement. They will all be revealed; they will all be read; all of them will be heard. O what embarrassment and shame I will experience on that day!
2) How many hidden sins that I myself did not even realize I had will be revealed then? How much inner wickedness that I never even considered will be made manifest? What possible excuse will I then be able to give for these things?
3) At that time God will place all the blessings and graces He gave me on one side, and on the other side He will place my sins and the bad use I made of the Mysteries, of His holy Body and Blood, of the inspirations and enlightenment He sent me, and of all His other gracees. What fear and despair will envelop me then!

   /Withdraw to some quiet and peaceful place today, even if just for a short while, and examine your conscience carefully, not only in order to find your inner passions, but also to examine the confessions you have made in the past and find your unconfessed sins. Then go to your Spiritual Father in order to confess them and be corrected in everything./

* Day 16
** Concerning the Separation of the Righteous and the Sinners
1) In this life, both the innocent and the guilty, the righteous and the sinners, live together, and after death, they are all alike buried. But then, the righteous will be separated from the sinners by the angels. At the right will be the righteous and probably those people that I made fun of in this life.
2) At the left will be the sinners and probably those people with whom I committed sin. 
3) In what place will I be found?

   /Have reverence for the angels, and certainly for your Guardian Angel. Ask him to separate your from the sinners on that day and to bring you to the right of Jesus. Be obedient to the inspirations your Guardian Angel sends you unto the working of virtue./

* Day 17
** Concerning the Final Verdict
1) After the seperation of the sinners from the righteous, Jesus Christ will pronounce a verdict that will be forever permanent and unshakable.
2) It will be a verdict put into immediate effect.
3) It will be a verdict given once and for ever - an eternal curse for those who sinned and did not want to repent and amend themselves, and an eternal
   blessing to those who did not sin, or to those that did sin but then repented and amended their ways.

   /Humble yourself before God. Repent and ask Him for forgiveness, entreating Him to deliver you from that condemnation./
* Day 18
** Concerning the Preciousness of Time
1) One single moment of time is just as precious as all of time. This is because the soul that is bereft of God on account of sin can in a single moment
   obtain Him. Therefore, say this to yourself: How much good can I do this very day, but do nothing about it?
2) This day will pass, and it will never come again.
3) I will have to give an account for this very day. How is it that I am not worried about this? And this applies to every single moment of my life.
   Woe to me, if I use the present time for evil.

   /Consider making a spiritual profit today and accumulating great wealth by performing many virtuous deeds. Make use of all of the causes of the virtues/
   /that you can in every work you do. For example, during the Divine Liturgy, put into practice acts of worship, faith, and thanksgiving for the sake of/
   /acquiring love, obedience, and the like./
* Day 19
** Concerning Hell
1) What is hell? It is a dungeon full of darkness where the damned live in chains, without a single hope of being set free.
2) It is a dwelling full of fire, always ablaze, that will never go out.
3) It is a place of all the chastisements, where there will always be all of the punishments, and where there will never be any relief

   /Repent today because of your sins, remembering the punishments of hell which you should now be experiencing, were it not for the compassion of the Lord./
* Day 20
** Concerning the State of the Damned
1) What do the damned do in hell? They obtain the infinite evil of sin which, at the present, they do not care about.
2) They receive the punishment for sin which, at the present, they do not consider.
3) They curse the cause of sin which, at the present, they do not avoid. O the wretched life of the damned! It would have been better for
   them to return to non-being than to exist in hell.

   /Avoid every thing that causes you to fall into sin. Offer up your entire will to God and surrender it to His will. Ask God and the most-holy Theotokos to/
   /save you from sin, which is the cause of hell./
* Day 21
** Concerning the Uncertainty of Salvation
1) I am worthy of hell because I have sinned, and I am not certain if God has forgiven my sins.
2) I may go to hell if I do not repent, and I am not certain if I will repent and resist the causes of sin.
3) I will go to hell if I do not change my life and produce fruits of repentance, but I am not certain if I will change my life before I die. Alas!
   If, after confession, on account of my bad habit and with my internal consent, I fall again into that sin which I committed so many times, what
   will become of me?

   /Make a firm resolution never to sin again. Be corrected of that sin which is easy for you to commit and to which your will is inclined, for sin makes/
   /you even more uncertain of your salvation./
* Day 22
** Concerning the Number of Those in Hell
1) It is easy to go to hell, for the road to hell is very wide, and many go that way, just as Christ says.
2) It is difficult to be saved, for the gate of Paradise is very narrow, and there are few that enter through it, as Christ says.
3) From the beginning of the world until now, most have gone to hell, as the Fathers say. And still the majority of future people will go to hell.
   What do I think will happen to me?

   /You must struggle to be like the few and the chosen rather than like the many and the condemned./
* Day 23
** Concerning the Confession of a Person in Hell
1) Every person condemned to hell will say the following: God did many things in order to save me. How many benefactions of nature and of grace did
   He give me? Am I not obligated to love Him? How many inspirations, enlightenments, and mysteries did He give me, in order to place me on the road
   to salvation? He consoled me with so many promises. He instilled fear in me with so many warnings. He put up with me for so long in my repentance.
   But all is in vain because of my hardheartedness. Therefore, I am justly punished.
2) I could have been saved had I done but a few things:
   - Had I cut off the cause of sin from the very beginning.
   - Had I been steadfast in my resolution to never sin.
   Once courageous resolution, one general confession, one remorseful repentance, would have put me in heaven.
3) I elected to be punished on account of that which is nothing. For the sake of a single moment of hedonistic pleasure I am here experiencing eternal
   punishment. With my eyes wide open I was plunged into a abyss of flames, and justly so. This is the penalty for not listening to all of the counsels
   of the Spiritual Fathers, the voice of my conscience, and the compassion and patience of God.

   /Make sure to confess all of your sins and repent as you should in order to be spared that useless confession and repentance of those in hell./
* Day 24
** Concerning Eternal Hell
1) Hell is for someone to be deprived of God forever.
2) Hell is for someone to burn in fire forever.
3) Hell is for someone to be in despair forever, with no remedy. O how fearful this 'forever' is! How unbearable this eternity!

   /Give thanks to the Lord for having mercy on you and for giving you time for repentance. Ask that the Lord will imprint on your mind the remembrance/
   /of the eternity of hell, for this alone is sufficient to bring you to reason./
* Day 25
** Concerning Procrastination
1) I have sinned. Therefore, either hell, or repentance. How is it that I still sin and live happily, having the hope that I might be able to repent? Alas! But what makes me so certain that I will be successful in this, that I will have time to repent?
2) If I am given the time to repent, will I be able to repent as I should?
3) And if I repent, who knows if I will fall into sin again?

   /Think about the time God has given you so that you may use it unto His glory and unto the salvation of your soul. Do not waste even a single hour of your allotted time./
* Day 26
** Concerning Paradise
1) Upon entering Paradise, I will immediately possess every good thing, without a single bad thing. I will rejoice without a single trouble. O how great will be my consolation, my joy, and my delight!
2) I will then have everything good, and I will rejoice in the company of my Jesus, of the most-holy Theotokos, of the company of the angels, and of the Saints. O how glorious and beautiful my company will be!
3) I will rejoice eternally, with no danger of ever losing such joy. O inexpressible joy!

   /In all of your sorrows and joys, say the following:/
              /"O Paradise, Paradise! When will I enjoy you?"/
   /And in comparison to Paradise, you will learn to scorn all of the good of the earth and to willingly endure every misfortune and passion./
* Day 27
** Concerning the Way to Paradise
1) There are only two ways to Paradise, innocence and repentance. So, have I preserved my baptismal innocence until now? No. For I have dirtied and lost it on account of my many sins.
2) And have I ever sufficiently repented for these sins? Have I undertaken any hardships? Alas! Instead, I have avoided every difficulty and sought after the pleasures and comforts of my body.
3) Yes, I do want to enter into Paradise, but by which way shall I enter? By one of the two, either by innocence or by repentance. I cannot enter by the way of innocence, and I do not wish to enter by the
   way of repentance. How, then, can I be saved and enjoy Paradise?

   /Envision heaven and think about it, saying: "Look where I will be for all ages, if only I repent as I should."/
* Day 28 
** Concerning the Acquisition of Paradise
1) God asks very little of me for Him to give me Paradise. It is enough if I just keep His law, a law most easy, most righteous, and most sweet.
2) The little that God asks of me He Himself assists by the grace of His inspirations, by His virtue, and by the power of His examples.
3) God repays this small effort of mine with an eternal prize. He repays a few hardships and troubles with eternal and perpetual grace.
   He repays a few struggles with an eternal reward. He repays a few sufferings with eternal glory.

   /So, you will be justly punished, if you are negligent in so little and lose Paradise./
* Day 29 
** Concerning the Immortality of the Soul and of the Body after the Resurrection
1) Every person will go to some place in the next life, either to Paradise or to hell, remaining there immortal in soul and body. Every person prepares that place for himself from this life, either by his good works or by his evil works.s
2) By a little hedonistic pleasure and fleeting comforts the devil calls me to place my immortality in hell, and I go along with him.
3) The Lord cries out to me to place my immortality in Paradise by a little repentance, but I do not go along with Him. O what a fool I am! O how ignorant I am!

   /Today, think frequently about your immortality. And in order for you to receive your immortality happily in Paradise, have the most holy Theotokos as a mediator before God./
* Day 30 
** Concerning the Reply of Each Person's Conscience
1) I ask my conscience: For what purpose did God bring me into the world? It replies that God brought me into the world in order to be saved.
2) I ask my conscience: How many means did God provide for me so that I might be saved? It replies that God gave me an infinite amount of means, both according to nature and according to grace, for me to be saved.
3) I ask my conscience: What have I done until now in order to be saved? It replies that I have done the worst things possible, as if my purpose for being born into the world was in order to be damned.\

   /Confess, my brother, condemn the evil you have committed and decide to live accordingly to the commandments of the Lord, for this/
   /very hour may be the last hour of your life. Offer your entire self to God, together with the powers of your soul and the senses of your body./
