#+TITLE My Org Mode
#+AUTHOR Ryan Harvey
* org
** My future/planned Org experience
*** What I plan to do with org
1. Schedule things, keep up to date with certain habits and todos
2. Take notes for classes more efficiently and productively, find ways to reproduce these notes into formats
3. Find uses of org-mode _online_

*** What will I do to accomplish these things
1. First finish the tutorial that is given, taking notes along the way and using org mode *everyday*
2. Making sure to not miss any keybinding or syntax for org-mode, because it is all helpful
3. Watching youtube videos and using chat gpt to optimize the learning experience and catch non-obvious things 

** Tips by myself 
1. Play around with it, instead of just taking it seriously with notes, because playing around is more enjoyable
2. Figure out how to organize files for notes/todos/etc.
   * Can leave this off for later
     It will probably be more clear later on
   * Will most assuredly use org files outside of ~/gh/myorg/, for example in classes and such
     This will be beneficial for note-taking, but also just laying out todos anywhere _if_I_want_to_take_that_route_
*** habits
1. book reading
2. praying
3. studying throughout week efficiently
4. calling friends/family
5. Staying on top of hygiene (mainly acne-treatment)
6. Mobility
7. good habits that put me in a good mood (trying to do something kind for someone, fixing bed, etc.)
8. habits that are good for my soul and eternity (remembrance of death, love for Christ, continual suffering for Him)
** Useful tips by experienced me
*** *git*
- When logging off a computer     (or leaving it)       git push _everything_ before logging off!
- When going from computer to laptop or vice versa, git pull _everything_ before changing things!
** For now
**** What I plan to do in the future
***** Using journal for daily tasks/updating todos, nexts, goals, etc.
This consists of opening a new journal everyday, starting out by filling in my morning routine to-do list,
then updating todos that need to be updated. At the end of the day I will have my evening routine, and throughout
the day I can journal small things that I want to express in words or for any particular reason, maybe some advice on
improving my org-mode usage.
***** Using agenda to have schedule outlined with todos/habits/nexts, etc.
Agenda view will help me greatly to schedule everything out nicely, and it can also help me keep track of
daily habits, weekly habits, and so on. [[* habits][my list of habits]]
**** Notetaking p1
***** What is org-mode?
org-mode is a toolbox for all sorts of things:
1. structuring documents
2. literate programming and research facilities 
3. TODO lists manager
4. Organize tasks in a flexible way
5. Can export as different formats such as HTML, LaTeX, Open Document, and Markdown.
6. source blocks with evaluation
7. Integrated with Emacs calendar and diary
8. Can be used to implement many different project planning schemes
9. Ultimately a organizer for things
***** C-c is essential
****** C-c is used for a lot of commands, especially in navigation through org-mode.
Think of the navigation simply:
1. C-c C-n for "next" to go to the next closest heading
2. C-c C-p for "previous" to go to the closest previous heading
3. C-c C-f for "forward" to go to nearest heading of same level
4. C-c C-b for "backward" to go to nearest previous heading of same level
5. C-c C-u for "up" to go to previous heading of higher level
****** C-c C-c also has a lot of functions, depending on circumstance
***** Inserting headings/items/rows
To auto-generate a heading/item/row that you are currently on, press M-RET, but to create a new heading at the end of subtree, press C-RET
***** Todo headings
M-S-RET inserts a TODO heading as the largest header at the end of subtree one is at,
but to have it respect your position, C-S-RET will have it lower in the subtrees depending on position
***** promoting and demoting
promoting and demoting is done with M-VIMMOTIONLEFT/RIGHT for a single header
M-UP/DOWN is used to move subtree up or down in position/rank
M-S-L/R is to promote and demote currect subtree by one level
***** narrowing and widening
if you want to narrow a buffer to only show one subtree, C-x n s for "narrow subtree" is your friend
if you want to narrow a buffer to only show currect block, C-x n b for "narrow block" is your friend
To cancel these changes and look at your full masterpiece, do C-x n w for "narrow widen"
***** toggle heading
Whether to promote text/lists to headings or to demote headings as text, C-c * will get the job done for ya
***** Lists
****** Types of lists
- Unordered lists
- Ordered lists (1. 2. or 1) 2))
- Description list
  uses :: to distinguish term from the description
  example:
  * Elijah Wood :: He plays Frodo
  * Sean Astin :: He plays Sam, Frodo's friend.  I still remember him
       very well from his role as Mikey Walsh in /The Goonies/.
