#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-16 Tue> 14:38
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Reflection
stayed up way too late last night trying to figure out an assignment for cs245, finished it this morning but the whole process was painful, let's not do that again.
**** done Duolingo
*** done Evening
**** done Reflection
Today wasn't the best, I finished up things but it was not structured. My fault. All in all, tomorrow shall be better, Lord willing.
**** done Mobility
** Read
*** Bible 
**** Old Testament (Lv 10-12)
The first chapter was about Aaron's sons disobeying the worship of the Lord, and they were burned up in fire.

The next two chapters were about cleanliness, and how God tells us to be cleanly, for this transmitted over to
the era of grace where we are both physically and spiritually cleaned in Christ through the Church.
**** Psalms (34:1-16)
This psalm is a great entreatment to the Lord, of how He shall deliver His servant from those who pursue him.

Need to keep this one in the belt.
**** Proverbs (7:1-6)
A Son with Discernment

This section is a father entreating the son that he keep the commandments of the Lord, as he will live then.
~And you will live, and my words as the pupils of your eyes; And put them around your fingers And write them upon the breadth of your heart.~
**** New Testament (Mt 23:1-22)
Christ gives a great speech against the scribes and the Pharisees. Very powerful.
*** The Divine Liturgy
**** starting page: 15
**** ending page  : 23
**** summarization: 
** Extra
** Plan [3/5]
- [X] finish a02
- [ ] read bible and liturgy book
- [ ] ciss245 notes
- [X] upload a02, q03, q04, q05
- [X] Typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |  75 |  83 |  25 |
  | 113 | 100 |  25 |
  |  99 |  96 |  25 |
  |  89 |  94 |  25 |
  | 103 | 100 |  25 |
  |  74 |  90 |  25 |
  | 112 |  99 |  25 |
  |  89 |  93 |  25 |
  |  91 |  97 |  25 |
  |  97 |  97 |  25 |
  |  96 |  97 |  25 |
  | 101 |  96 |  25 |
  |  92 |  99 |  25 |
  |  97 |  97 |  25 |
  | 131 | 100 |  10 |
  | 119 | 100 |  10 |
