#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-19 Fri> 06:05
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Duolingo
**** done Reflection
Last night was completely wasted, when I could've gotten very good work done. So now, I will have the analogy of jumping into water when I need to get started on something. Sure, I can hesisitate for a few seconds, but it's either I jump in or somebody pushes me in while I'm not ready (cramming for a class).
**** done Mobility
*** done Evening
**** done Reflection
Today was great, had a lot of work done, and ended off the day with playing ping pong. Great day should imitate in the future.

I'm ahead in the notes, but that's not the goal, I will slow down and absorb everything, but keep trudging through, not stopping to let others catch up, because I am in love with the notes and learning so that I can eventually make Galaxian!

Also, I might work for Liow, which will get me a better understaning of the Fedora machine and other things about the CS Club. This is a great opportunity especially since I'm only a freshman. God blessed me, may I continue to praise Him and hold onto Him, for He is my life.
**** done Mobility
**** done Prayer
** Read
*** Bible 
**** Old Testament (Lv 16-18)
This reading was dense. First, it tells of the sacrifice Aaron started that was important for Jews and the coming Christ. This sacrifice was an annual one, to be for all peoples for the forgiveness of their sins. It was taken very seriously. The next chapter was about the sanctity of blood, that it should be regarded with respect and not eaten, so as to prepare the way for Christ. The last chapter was a very compact yet covering all sexually immoral sins.
**** Psalms (36:1-20)
This psalm compares the evil with the one who trusts in the Lord.
**** Proverbs (7:21-24)
This psalm finishes the story of a woman trapping the man into fornication. Grueling images.
**** New Testament (Mt 24:29-51)
This section is all about the End, where Christ will come again in glory. He tells his disciples what will happen in the End, who will experience it, when it will happen (anytime, so be on watch!), where it will happen, and why it will happen. (the 5 W's)
*** The Divine Liturgy
**** starting page: 38
**** ending page  : 48
**** summarization: 
Sacred icons were mentioned, and how they relate to the words we read in the Bible.

Also the priest is related to Christ, for the priest is the agent through whom Christ works through. The Holy Trinity together works together in the Liturgy but Christ is the one working through the priest, for as Christ is human so He saves the human race.
** Extra
** Plan [9/9]
- [X] reading plan
- [X] engl discussion board post
- [X] hist notes on ch3
  will read small bits of this and take good notes for cougar bowl (shouldn't care too much for this class)
- [X] verify morning interview with library
- [X] struct notes
- [X] typedef notes
- [X] math notes
- [X] math hmwk
  will do this tmrw along with other things
- [X] typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |  92 |  95 |  10 |
  |  92 |  95 |  10 |
  | 106 |  97 |  10 |
  | 119 | 100 |  10 |
  |  97 | 100 |  10 |
  | 101 | 100 |  25 |
