#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-17 Wed> 08:14
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Reflection
I can't stop sleeping 9+ hours. I need to change alarm again, I'm sleeping way too much.
**** done Duolingo
**** done Mobility
*** done Evening
**** done Reflection
Today was full of troubles. At my first class I threw remarks against someone and all throughout the day I would slander people and pick fights. I think it was because of my lack of prayer today. Lord, have mercy.
**** done Mobility
just some toe stretches before bed.
**** done Prayer
** Read
*** Bible 
**** Old Testament (Lv 13)
This chapter was about leprosy and how it makes one unclean. This ties in very well with Christ's message, in how sin defiles man like how leprosy defiles a body. 
**** Psalms (34:17-28)
The rest of this psalm is asking God to deliver them from their enemies, for they're deceitful and they don't follow the righteousness that God made them for.
**** Proverbs (7:7-12)
This reading is the beginning of a section called _A Son with Discernment_

It tells of the base woman who "traps" men like how animals are trapped. This section sets up a scene that is very descriptive and lays out human nature well.
**** New Testament (Mt 23:23-39)
This reading is Christ further condemning the scribes and Pharisees and anyone who condemns themselves by taking what God has given them and twisting it for their worldly concerns. This is an important warning for Orthodox Christians because with the true faith, we cannot let it be just another thing in our lives, we have to keep it, observe it very carefully, and edify ourselves and others about it, so as to not lose the faith in our heart, and condemn ourselves.
*** The Divine Liturgy
**** starting page: 23
**** ending page  : 28
**** summarization: 
Christ becomes one with us when we are made His children (through Baptism) and we eat His flesh (through the Eucharist). The Church is what Christ sent so that He could mingle Himself with His followers, those who have the true faith. Blessed is He who comes in the name of the Lord.
** Extra
*** todo paper 1 engl schedule
:PROPERTIES:
SCHEDULED: <2024-01-18 Thu +4d>
:END:
[[id:80806e7c-5b78-4b43-b62e-d25e1009b412][here]]
** Plan [5/5]
- [X] struct notes 245
  almost done with them, should finish tomorrow. I need to get in a good habit of stopping things when the day comes to an end. Because I can study tomorrow, and I may need to study more things before then.
- [X] Candide reading
- [X] plan paper 1 for engl
- [X] read bible and liturgy book
- [X] Typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  | 147 | 100 |  10 |
  | 100 |  98 |  10 |
  | 107 | 100 |  10 |
  | 100 | 100 |  25 |
  |  96 |  99 |  25 |
  |  96 |  98 |  25 |
  | 105 | 100 |  25 |
