#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-18 Thu> 06:05
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Reflection
Woke up in the middle of last night and asked Reed and Marc a crazy question that seemed coherent in my sleep, completely delirious.

I'm glad I woke up today at a decent time, I can get started on the day earlier and get plenty done.
**** done Duolingo
**** done Mobility
*** Evening
**** Reflection
**** Mobility
**** Prayer
** Read
*** Bible 
**** Old Testament (Lv 14; 15)
Ch14 was a continuation of the previous chapter on leprosy.

Ch15 was about a man and woman's discharge, which would make them unclean until evening. The notes brought to mind the woman who had suffered uncleanness for years and was healed by Christ when she touched His garment.
**** Psalms (35)
This psalm is about free will and the consequences of one using it poorly. Since consequences ultimately come down to the heart and the state of drawing further from God, they aren't obvious. We have to love righteousness, even if life is a struggle to do good. Life can be easier if one sins, sure, but eternity will outweigh and destroy a lawless life on earth.
**** Proverbs (7:13-20)
This is a continuation of yesterday's narrative of a base woman. This woman tempts the man to come make love with her until morning, for her husband is gone on a long trip. The ways of God shall be on this man, around his finger and as a sister, so as to guide him in this moment.
**** New Testament (Mt 24:1-28)
This is a packed chapter, and I haven't even finished it yet. Christ tells of the destruction of the temple, His second coming, and the times leading up to it. He tells that Christians will struggle, but those who endure to the end will be saved. He says there will be false prophets, saying that Christ Himself is in a particular place/time, but they miss the point, and they're wolves scheming and evil plot against people's souls.
*** The Divine Liturgy
**** starting page: 28
**** ending page  : 38
**** summarization: 
Three notecards were added. First, this reading talked of reconciliation before the Sacrifice, for Christ values the love of our fellow man before an unworthy sacrifice. Second, Kairos was mentioned, a service in the liturgy that translates to God's timing, of which Christ came into this world and everything was renewed, the Timeless One came into time, so as to renew all of man and open up the heavens. Between this and the third note was the Theotokos as the "gate that faces the east." The third note was of the Cross, the glory of Christ, of which Orthodox Christians make the sign of to show that Christ has conquered the enemy, and bestowed life unto all. We shall take great care of this sign, for Christ has given it to us as a weapon, and the more care we show the sign when we use it (especially to know that it's what Christ Himself suffered on to then resurrect) the more benefits God will bless us with as we use it as a weapon against the demons.
*** Candide
**** starting chapter: 20
**** ending page     : 410
**** summarization: 
** Extra
** Plan [0/6]
- [ ] ENGL paper 1 work
- [ ] Candide reading
- [ ] structure notes finish
- [ ] typedef notes start
- [ ] take notes in hist and prepare for cougar bowl
- [ ] Typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |     |     |     |
