#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-24 Wed> 06:14
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Duolingo
**** done Reflection
Good day tomorrow, an even better day today, God-willing. I want to grow in the fasts.

One thing I have to realize is that any sort of imaginings I have are impeding my progress. If I pray, I should have my prayer rope along with me, and if I'm not focus, I focus instead on the jesus prayer and then return where I left off.
**** done Mobility
*** Evening
**** Reflection
**** Mobility
**** Prayer
** Read
*** Bible 
**** Old Testament (Nm 1; 2)
The first chapter was a census of the people, which carried over in the next chapter for the position of the tribes of Israel around the tabernacle.
**** Psalms (39)
This psalm is a prophecy of the Incarnation.

This is explained in the footnotes, which is eye-opening, because I have this false assumption that the psalm's voice is of just any faithful, when it represents Christ at times very clearly.
**** Proverbs (8:17-21)
This reading tells of what Wisdom possesses (and how it's better than all worldly riches) and how Wisdom gives His gifts (to those who love Wisdom).
**** New Testament (Mt 26:47-75)
Christ was arrested, tried by the Pharisees, and Peter denied Him three times.
*** The Divine Liturgy
**** starting page: 78
**** ending page  : 90
**** summarization: 
** Extra
** Plan [/]
- [ ] 
- [ ] typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |     |     |     |
