#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-21 Sun> 11:38
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Duolingo
**** done Reflection
set an alarm for church, was in PM. So dumb, I don't even know how to explain that to Fr.
**** done Mobility
*** Evening
**** Reflection
**** Mobility
**** Prayer
** Read
*** Bible 
**** Old Testament (Lv 19-21)
Ch19 is a lot of beautiful exhortations and all of them are followed with, ~for I am the Lord your God~. Ch20 is about penalties for lawbreakers. Ch21 is about conduct for priests.
**** Old Testament (Lv 22; 23)
Lv 22 talks more of priestly orders. Lv 23 is about the feasts of the Lord. 
**** Psalms (36:21-40)
beautiful psalm
**** Psalms (37:1-11)
this is a familiar psalm that I read for my morning prayers.
**** Proverbs (7:25-27)
This proverb ends the teaching to stay away from an unrighteous woman, where the Teacher exhorts the faithful one to hold fast to the words of His mouth, lest they follow her, whose house is the road to Hades, leading down to the chambers of death.
**** Proverbs (8:1-5)
This is the introduction of a chapter that exalts wisdom, and personifies it as a woman exhorting men.
**** New Testament (Mt 25)
The first parable is the one of the Bridegroom coming a midnight, when the righteous and the unrighteous are sleeping, and the unrighteous aren't prepared for Him.

The next parable is one of the giving and receiving of talents. This parable tells of the fruitfulness of the Lord's servants, of which He will cast out and destroy the unfruitful ones, where there will be weeping and gnashing of teeth.

The last vision Christ gives is of the Last Judgement, where Christ will seperate the sheep from the goats, and He will reward the righteous and punish the unrighteous.
*** The Divine Liturgy
**** starting page: 48
**** ending page  : 63
**** summarization: 
This chapter was about the vesting of the celebrant and the symbolism and reality that goes on during and through the priest's vestments.
** Extra
** Plan [6/7]
- [X] read bible and divine liturgy book
- [X] stretch for 5 mins
- [X] finish math hmwk
- [ ] 245 notes
- [X] engl paper plan
- [X] hist study
- [X] typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |  99 |  99 |  25 |
  | 110 |  99 |  25 |
  | 111 | 100 |  25 |
  | 116 | 100 |  25 |
  |  97 |  95 |  25 |
