#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-23 Tue> 05:43
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Duolingo
**** done Reflection
I hadn't done Duolingo for three days, so I had to do six straight mini lessons to get my streak back (I'm at day 200). Also, I finally woke up early today, I think today will be structured and well productive, God willing.
**** done Mobility
*** Evening
**** Reflection
**** Mobility
**** Prayer
** Read
*** Bible 
**** Old Testament (Lv 26; 27)
Lv 26 starts with a blessing for the obedient and then a horrific punishment for the disobedient. This reminds me of the Mother of God, who had completely given up her will to the Lord's and shown the greatest obedience among all women, where John the Baptist thrived in asceticism for he too was obedient to the Lord.
Leviticus ended with a chapter on making vows to God, of which should be paid. For it is better to not vow than to not pay (Ecclesiastes).
**** Psalms (38)
This is the psalm of a sojourner. A sojourner in this world awaiting the world to come.
**** Proverbs (8:11-16)
By Wisdom, discernment and strength is given. Kings reign by wisdom, princes write of righteousness, noblemen become great by wisdom, and monarchs have power by Him.
**** New Testament (Mt 26:26-46)
The Eucharist, Prediction of Peter's Denial, and Gethsemane.
*** The Divine Liturgy
**** starting page: 71
**** ending page  : 78
**** summarization: 
This section was on the cutting up of the prosphora is preparation for the Eucharist. Christ's death and resurrection were mentioned, and great glory was revealed through this.
** Extra
** Plan [3/5]
- [X] engl study
- [X] hist study
- [ ] math answer check w Robert
- [-] ciss245
  - [ ] a03 start
  - [X] q07 
  - [X] q2101
- [X] typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |  88 |  97 |  25 |
  |  92 |  99 |  25 |
  |  83 |  96 |  25 |
  |  94 |  99 |  25 |
  |  96 |  99 |  25 |
  | 103 |  99 |  25 |
  |  96 |  98 |  25 |
  | 115 | 100 |  25 |
