#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-25 Thu> 05:34
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Duolingo
**** done Reflection
should get my keyboard today. Practice will be easy, hopefully. I need rest.

All in all, I pray the Lord gives me a sinless day, in group settings especially I get carried away.
**** done Mobility
*** Evening
**** Reflection
**** Mobility
**** Prayer
** Read
*** Bible 
**** Old Testament (Nm 3:1-4:33)
Nm 3 is history on what the Lord did for the extra amount of firstborns compared to the # of Levites.

Nm 4 is continuing telling of the other families ( from the tribe of Levi ) that got a headcount and will serve in the tabernacle for a specialized service.
**** Psalms (40)
**** Proverbs (8:22-26)
**** New Testament (Mt 27:1-26)
Christ is taken up to Pontius Pilate, where He was speechless against the false accusations. Pontius Pilate could find no wrong in him, so Pilate decided to give the Jews a choice: release Barabbas, a merciless criminal, or the just Christ? (Barabbas means son of the father, in this case the devil is the father) The jews chose Barabbas to be released, because the Truth, Christ, was not in line with their worldly thinking.
*** The Divine Liturgy
**** starting page: 90
**** ending page  : 106
**** summarization: 
** Extra
** Plan [3/9]
- [ ] read divine liturgy book
- [X] have cougar bowl paper ready for hist today 
- [ ] do more a03
- [X] get keyboard from mail
  amazing
- [ ] do some classes/objects notes
- [ ] set up ping pong
- [ ] read and prepare for engl tmrw
- [ ] create discussion post for engl
- [X] typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  | 119 | 100 |  10 |
  |  98 | 100 |  10 |
  |  90 |  91 |  10 |
  | 105 | 100 |  10 |
  | 101 | 100 |  10 |
  |  99 | 100 |  25 |
  |  99 | 100 |  25 |
