#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-31 Wed> 06:05
* log 
** daily
*** done [[https://goarch.org][morning prayer/Lives of the Saints/Lectionary]]
*** done duolingo
*** done morning reflection
I can just tell this morning is going to be hard. But I have to charge through this feeling. Getting back on schedule is going to feel like this.
*** done morning mobility
*** done morning shower
*** done evening shower
*** done evening reflection
Through my own evil volition of transgressing Christ's commandments, God humbled me. He allowed it so that I would be humbled. Do not humble me further Lord, let this be the last time. Instead, let me humble and reproach myself, and to always call to you in unceasing prayer, saying, Lord, have mercy.
*** done evening mobility
*** done evening prayer
** read
*** Bible 
**** Old Testament (Nm 7:1-8:4)
The twelve tribes of Israel gave their offering to the tabernacle, and all but one Levite arranged these gifts for the Tabernacle.
**** Psalms (43:1-9)
This reading is about the Lord protecting us, not the tools that we use to protect ourselves, because it is ultimately the Lord who is protecting us.
**** Proverbs (8:32-35)
Heed the Wisdom of the Father, for such a man is blessed. Such a man will keep his eyes on Him at all times.
**** New Testament (Mt 27:45-66)
Christ gives up His spirit on the cross. The veil of the temple was broken, and the saints rose from the dead. Many details I hadn't known before. A centurion, St. Longinos, was converted because of the glorious crucifixion. Then the chief priests ordered to Pilate that guards would protect the tomb from those who would steal Christ's body proclaiming He rose from the dead. Foolish mistake, for nothing could stop Him from rising from the dead.
*** The Divine Liturgy
**** starting page: 96
**** ending page  : 106
**** summarization: 
** extra
** plan [4/4]
- [X] redo math assignment
- [X] read ahead for engl
- [X] start engl paper 1, first subtheme
- [X] typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  | 100 |  97 |  25 |
  | 105 |  93 |  10 |
  | 101 |  96 |  25 |
  | 100 |  98 |  10 |
  | 102 | 100 |  25 |
  | 108 | 100 |  10 |
  
