#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-30 Tue> 06:09
* log 
** daily
*** done [[https://goarch.org][morning prayer/Lives of the Saints/Lectionary]]
*** done duolingo
*** done morning reflection
Finally! I wake up at a decent time. Now I can get back on schedule. It will be hard to jump back on but I'll make it, just as long as my school work is up to date I need not worry.
*** done morning mobility
*** done morning shower
*** evening shower
*** evening reflection
*** evening mobility
*** evening prayer
** read
*** Bible 
**** Old Testament (Nm 4:34-6:26)
The law against unfaithful wives and of the extraordinary vow (asceticism) was given. Then the reading ended off with the great priestly blessing, which is in the Lord's name and is powerful and life-giving.

~The Lord bless you and keep you; the Lord make His face shine upon you, and be merciful to you; the Lord lift up His countenance upon you, and give you peace~
**** Psalms (41; 42)
**** Proverbs (8:27-31)
**** New Testament (Mt 27:27-44)
This is the beginning of the path to crucifixion of Christ. They mocked Christ with glorious titles, all of which Christ was worthy of, but their hardened hearts didn't let them see the Truth right before them.
*** The Divine Liturgy
**** starting page: 90
**** ending page  : 96
**** summarization: 
the departed, incense, and Christ clothed in majesty. (~The Lord has reigned. He has clothed Himself in majesty~)
** extra
** plan [1/7]
- [X] daily readings
- [ ] finish sections and prep for engl paper
  maybe start typing, but tomorrow should be the beginning of one page per day
- [ ] get ready for cougar bowl/read ch4/review last chapters/lectures.
- [ ] start a06
  when done with a06 we'll review past notes and then continue in the notes
- [ ] use pomodoro (move around during break)
- [ ] typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |     |     |     |
