#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-02-02 Fri> 05:41
* log 
** daily
*** done [[https://goarch.org][morning prayer/Lives of the Saints/Lectionary]]
*** done duolingo
*** done morning reflection
Glad I woke up earlier than usual, I should get some things done today ...
*** done morning mobility
*** done morning shower
*** done evening shower
*** done evening reflection
did a good amount today, Lord, have mercy
*** done evening mobility
*** done evening prayer
** read
*** Bible 
**** Old Testament (Nm 11:1-14:10)
the 11th chapter had the people grumbling against God and they were gluttonous for meat, very convienient that it's a fast day, and the Lord promised them meat for a month, so much so that they would regret asking for it. It ended up where people had meat between their teeth and the Lord struck them with a great plague.

the 12th and 13th chapter is one of the Lord promising the land of Canaan to the Israelites, but after sending spies there, the Canaanites seem to be formidable enemies.

the 14th chapter begins with the people rebelling against the Lord's favor of giving them the land of Canaan. the people stone those who want to keep the Lord's will for them.
**** Psalms (44)
This psalm is a praise to Christ, describing a human that which is our King, and who is God, but His God (the Father) anointed Him ...
**** Proverbs (9:7-11)
This reading tells us not to reproach the evil man, lest he hate us, rather reproach the wise man, for he will love us for that.
**** New Testament (Mk 1:1-20)
Mark starts with John the Baptist, the fulfillment of Elijah returning (shown by the similar clothes and most importantly his actions). Christ is baptized by John and is then led into the wilderness by the Spirit. And then after John is imprisoned, Christ then starts his ministry, preaching to those to believe in the gospel, and gathering His disciples.
*** The Divine Liturgy
**** starting page: 110
**** ending page  : 117
**** summarization: 
this whole reading was of the peace that Christ brings. Peace is the characteristic of a godly man, it can be seen in all icons of godly men. There are levels of peace, and the highest peace is an inseperable bond of peace that comes from the love of God and the love to God.
** extra
** plan [5/5]
- [X] paper 1 progress
  will work on this tmrw
- [X] unsub from app
- [X] math hmwk progress
- [X] supernote pen watchout
- [X] typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  | 114 | 100 |  10 |
  | 106 |  93 |  10 |
  | 122 | 100 |  10 |
  |  98 |  99 |  25 |
  |  92 |  98 |  25 |
  |  99 | 100 |  25 |
  |  86 |  99 |  25 |
  | 103 | 100 |  25 |

