* New Years!!
I think back a year ago, and then a year before that, just to realize how crazy of a transformation it's been.
And it's not over, Christ will continue to strengthen me and transform me so that I'm changed into his likeness.
A year ago I was starting to truly want to know Christ, hence me and Lathon visiting our local Orthodox parish,
where we first met Fr. Michael and the parish members of St. Luke the Evangelist.
* todo [#A] Daily
:PROPERTIES:
DEADLINE: <2024-01-01 Mon>
:END:
** done Morning
*** done Prayer/Lives of the Saints/Lectionary
*** done Thanksgiving
Lord, I have experienced many New Years celebrations and days, but this one was the best.
I enjoyed it in Your Church, which You sanctified so that man might know You. Glory to
Your incomprehensible condenscension, O Christ.
*** done Reflection
The last two years I was at party's celebrating New Years, but what better way to celebrate a new
year since Christ's birth than to go to His Church and glorify Him and His Saints. The feast of
His circumcision and St. Basil the Great were soul-filling today. I'm truly being changed by His
divine love.
*** done Mobility
** Daily TODOs
*** done Duolingo
*** done Typing
| wpm | accuracy | word count |
| 104 |       97 |         25 |
|  98 |       98 |         25 |
|  85 |       98 |         25 |
|  96 |       98 |         25 |
|  99 |       98 |         25 |
|  84 |       94 |         25 |
|  85 |       98 |         25 |
|  99 |       99 |         25 |
| 117 |      100 |         10 |
| 107 |      100 |         10 |
| 103 |      100 |         10 |
| 116 |      100 |         10 |
| 109 |      100 |         10 |
| 106 |      100 |         10 |
| 112 |      100 |         10 |
*** done Bible 
**** Old Testament
**** Psalms
**** Proverbs
**** New Testament
*** Read
**** Input book(s) and all info here:
***** Algorithms to Live By
****** starting page: 149
****** ending page  : 169
****** summarization: 
***** When God is Not There
****** starting page: 0
****** ending page  : 31
****** summarization:
** Evening
*** Reflection
*** Thanks
*** Remembrance 
*** Mobility
* todo [#A] Plan [/]
:PROPERTIES:
DEADLINE: <2024-01-01 Mon>
:END:
- [ ] 
