#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-10 Wed> 08:03
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Thanksgiving
The Lord had kept me asleep a little longer, may my day be fruitful Lord, with this rest You have given me.
**** done Reflection
Last hard day of the week, mondays and wednesdays will be all over the place and friday is barely better.
Lord, grant us the strength to finish out this day and the week well.
**** done Duolingo
**** done Mobility
*** Evening
**** Typing
**** Mobility
**** Remembrance 
**** Reflection
**** Thanksgiving
** Plan [0/3]
- [ ] Get headphones from mailbox
- [ ] Go find and talk to physics professor about calc-based physics
  - [ ] after ciss350
- [ ] Typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |     |     |     |
** Read
*** Bible 
**** Old Testament (Ex 33-34)
Moses has a conversation with God, and in this conversation God says that He will have mercy on those that He has mercy on, and judge those whom He judges, for He only knows the hearts of people. Then Moses wants to see God's face of which He cannot, for nobody can see His face and live (talking of God's essence).

In the next chapter (Ex 34), Moses goes up to Mt. Sinai again after having broken the last stones of commandments and also after having been commanded by God to do so. Moses, after having received the next stones, heard the Lord proclaim beautiful praise to the Lord. The Son gives praise unto the Father (of which verses are in daily prayers). The covenant is renewed here, where God promises to lead the Israelites out of the land of which they sojourn, and into Jerusalem. Then, when Moses comes down from Mt. Sinai, his face shines with glory. The notes says that this glory was to point the jews to Christ, and that it was not the Law that was the problem, but the hardness of their hearts, for they didn't see Christ in the Law. 
**** Psalms (30:15-25)
The rest of this psalm is a supplication to the Lord, of which the servant asks for God's mercy, and also that His judgement be passed. The speaker also asks that the rest of the Lord's servants should love the Lord, for He seeks out truth.
**** Proverbs (6:13-16)
This section abhors the lazy and slothful, for poverty will come to them as an evil traveler. But blessed be the diligent, for their harvest shall come to them as a fountain.
**** New Testament (Mt 20:1-16)
This was a parable of a landowner of a vineyard, of which he hired workers to tend to the vineyard. The landlord went to the marketplace throughout the day to hire more servants for his vineyard, even unto the end of the day he did this. At the end of the day, all of the servants were paid the same, for it seemed good to the landlord. The servants who had been working all day complained to the landowner, for they were paid the same as the last servants. The landowner represents Christ, of which He proclaimed, "~The last are first and the first are last, many are called but few are chosen.~" This can apply to many things but just because someone has been in the Church longer doesn't grant them to be better or more deserving than one who joins the Church later in life after having been godless perhaps their whole life, for thinking this way is limiting God's mercy and is in err of who God truly is.
*** When God Is Not There
**** starting page: 121
**** ending page  : 139
**** summarization: 
The chapter starts off with a woman who lost her child, of which was her whole life. This woman wasn't religious, and believed that her child was gone forever. But someone at the funeral whispered in her ear that her child was alive. She didn't notice this then, but at a later time. The idea of her child being alive was more consoling than the hundreds of other whispers given to her, because she wanted ultimately to know the state of her daughter, was she eternally cast into nothingness? Or was she with Christ, of whom the mother should now totally focus on, in hopes to commune again with her daughter, and not lose hope in this life for the life to come. If there is a God, whom has taken her child into eternal care in His infinite love, then she wants to live for this God, the God that fully encapsulates Love. 
** Extra
