#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-11 Thu> 07:43
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Thanksgiving
I lay down and slept, I awoke, for the Lord will help me.
**** done Reflection
Magnesium is what I took before bed yesterday and I happened to wake up fully refreshed, so I'll keep that in mind for the future. Also, getting the virtual machine set up was a huge win, just wanted to acknowledge that.
**** done Duolingo
**** done Mobility
*** Evening
**** Typing
**** Mobility
**** Remembrance 
**** Reflection
**** Thanksgiving
** Plan [3/4]
- [X] hist take lecture notes
- [X] get headphones from mailbox
  Will have to wait until tomorrow until order is automatically refunded to order again at correct address.
- [ ] ciss245
- [X] Typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  | 106 | 100 |  25 |
  |  98 |  97 |  25 |
  |  91 |  98 |  25 |
  |  89 |  99 |  25 |
  |  88 |  96 |  25 |
  | 100 |  97 |  25 |
** Read
*** Bible 
**** Old Testament (Ex 35-37)
Ex 35 has the people giving all that was needed to build the temple, of which they gave exceedingly.

Ex 36, 37 are of the building of the temple, specifically garments and curtains.
**** Psalms (31)
This psalm prefigures baptism, the first verses emphasize the blessings of baptism, the next are the responsibilities of the baptized, and the rest is Christ's response to the faithfulness of the one baptized.
**** Proverbs (6:17-19)
This section teaches that a lawless man who constantly schemes evil things will have destruction come upon him, a deep and incurable wound because of his perverted will.
**** New Testament (Mt 20:17-34)
Christ begins by foretelling his crucifixion to the disciples.

Then the mother of James and John entreated Christ so that they would sit at his right and left hand in heaven. Christ says that this is not His to arbitrarily give, but to drink of the cup of the cross and to die in baptism is what they're called to do.

Then Christ tells His disciples, whoever wants to be great among you must be the servant and slave to you. Then Christ heals two blind men out of Jericho.
*** When God Is Not There
**** starting page: 139
**** ending page  : 153
**** summarization: 
The first story was of a young child who was suffering greatly, had died three times, and none of the best doctors could save her. But it was mentioned in this section that even the antidote of the doctors would eventually end in death, whereas God, when received, gives eternal life.

The second story was of a girl who had become brain dead, the priest fought with the personal dilemma of donating organs, because that was one of the paths that was possible for the parents to take. After talking to the doctor and praying, they decided to donate her organs, unfortunately, it was too late. But the priest came away from that situation with a different outlook on donating organs. That it is a greater love to give yourself so that someone else can have life, it's only a personal dilemma when it comes to you possibly receiving that donation.
** Extra
