#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-12 Fri> 07:06
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Thanksgiving
I lay down and slept, I awoke, for the Lord will help me.
**** done Reflection
Friday ... I just need to get to work on 245 notes, about two or more a week should keep me on track,
this semester will be harder than last semester and more crucial to my learning of c++, so I have to
take these notes very carefully yet diligently.
**** done Duolingo
**** done Mobility
*** Evening
**** Typing
**** Remembrance 
**** Reflection
**** Thanksgiving
**** Mobility
** Plan [/]
- [ ] 
- [ ] Typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |     |     |     |
** Read
*** Bible 
**** Old Testament (Ex 38-40)
This was the ending of Exodus, where the tabernacle was finished and it was presented to Moses. Moses then set it up and followed the Lord in how it should be used liturgically. It ended like this, ~For before all Israel, throughout all their journeys, the cloud was above the tabernacle by day, and fire was over it by night.~
**** Psalms (32:1-12)
This psalm is full of praise, it would be a good one to remember and sing throughout the day.
**** Proverbs (6:20-25)
This psalm continues from yesterday, talking of the lawless man.
~A haughty eye, an unrighteous tongue, / Hands that shed righteous blood, / A heart that devises evil thoughts, / And feet that hasten to do evil; / As a false witness he kindles injustice / And causes quarrels between brethren. / My son, guard the laws of your father, / And do not depart from the rules of / your mother / But fasten them to your soul / continually / And wear them as a collar upon your neck.~
**** New Testament (Mt 21:1-22)
This chapter begins with Christ entering Jerusalem on a donkey, palm sunday. Even the children were crying "Hosanna to the Son of David!" So, when tried by the Pharisees, Christ said, "Yes. Have you never read, 'Out of the mouth of babes and nursing infants / You have perfected praise'?"

Christ then purifies the temple, for it was filled with worldly commerce.

Then Christ said to a fruitless fig tree "Let no fruit ever grow on you again." symbolizing a fruitless christian that was only ever posing as one when they are judged (it seems). Then Christ told His disciples to have faith unerring to be able to do what He just did.
*** When God Is Not There
**** starting page: 153
**** ending page  : 171
**** summarization: 
This chapter was about a plane crash. The bishop went there and felt useless, and the next morning he held a service for a feast, in which he ended with the Trisagion. Great questions arose within him, and he didn't bat them away nor fall into despair with them. Our God is one whom suffered in this world, alongside us, so that He might save those whom follow Him, those who love justice and righteousness, his flock. When we try to comprehend everything, and if we say that God is totally comprehendible, there would be no point in living. Experience, emotion, and doubts of faith are apart of our human nature, and these can't be fully explained with words. We can cry out to God, but we should never lose hope in Him. For throughout all time, God has delivered us from evil and pain through Christ, the God-man, who suffered for righteousness sake and for the ability for us to commune with Him, and drink His Body and Blood. We should never set our hope on this world, we should live for the other world in this life, in full hopes that God will save us from the sorrows of this life.
** Extra
