#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-13 Sat> 09:46
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Thanksgiving
I slept in, the Lord granted me rest after a hard week, now Lord, with this day You have given me, strengthen me to work according to Your will.
**** done Reflection
Slept in, so I changed my alarm so that won't happen.

I plan to do a lot today, get assignments done, finish up some reading, and keep on the 245 notes.
**** done Duolingo
**** done Mobility
*** done Evening
** Plan [4/4]
- [X] math hmwk
- [X] bible and Where Is God reading
- [X] ciss245 a01
  - [X] redo question 2 to refresh brain on loops more 
# - [ ] ciss245 notes
#   - [ ] finish recursion notes w/practice + notes
#   - [ ] start struct notes
- [X] Typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |  96 |  96 |  25 |
  |  98 |  96 |  25 |
  | 104 | 100 |  25 |
  |  92 |  99 |  25 |
  |  87 |  97 |  25 |
** Read
*** Bible 
**** Old Testament (Lv 1-4)
The beginning of Leviticus was about how to worship God in the OT. But this wasn't completely done away with, most of the symbols are seen typified in the Church today. It is also shown how the worship in antiquity helped the people to eventually come to worship their God in truth, and to have the only acceptable offering that was finalized on the Cross.
**** Psalms (32:13:22)
This psalm continued talks of how worldly power (however it's manifested) won't save someone when it comes to judgement from God. We shall hope in the Lord, and cry out, "Let Your mercy be upon us, O Lord, for we have set our hope on You."
**** Proverbs (6:26-31)
This reading is the beginning of a section called "Playing with fire" of which it entreats the man of God to not let the desire of a woman conquer him, for the value of a prostitute is as one meal in a lifetime. The man's soul is precious, and it should be guarded as such with the Lord's commandments.
**** New Testament (Mt 21:23-46)
Christ starts off by giving the Pharisees what they wanted, an answer to how He is an authority. He said, "which if you tell Me, I likewise will tell you by what authority I do these things: The baptism of John--where was it from? From heaven or from men?" The Pharisees were stooped, for to deny John the Baptist, a well-known prophet of good works according to Abraham's faith, would be to deny Abraham's faith, which was in Christ Jesus.

Christ then tells two more parables:
1. A son told his Father he would do the Father's will but he didn't, whereas the other son confessed he wouldn't do the Father's will but ends up doing it, who is in the right?
   The Pharisees say the second man, but this is condemnation for them.
2. The landowner of a vineyard lets people tend to it, while he travels to a far land. These people end up destroying all of the servants and eventually even the son of the landowner, so as to receive the vineyard for themselves. 
   But when the landowner comes back, he will punish them, the Pharisees said, again condemning themselves.
*** When God Is Not There
**** starting page: 171
**** ending page  : 193
**** summarization: 
Beautiful chapter talking of elderly wisdom and ultimately the wisdom that Christ brings, that we do not live for this life, though this life is necessary, just as the Cross was necessary for the Resurrection.
** Extra
