#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-15 Mon> 07:00
* log 
** Routine
*** done Morning
**** done Prayer/[[https://goarch.org][Lives of the Saints/Lectionary]]
**** done Thanksgiving
The Lord has blessed me with another day, I woke up and was immediately ridden with thoughts of passions, even during prayer I faltered to keep a good conscience, have mercy on me, O God. Purify my heart, that I may not stray from Your ordinances.
**** done Reflection
No school today, I should get plenty done, though. Most importantly I need to fix my prayer life, I cannot get distracted. Maybe I need to have my prayer rope in hand so that anytime I'm rushing I take a second to use the prayer rope until I'm focused again.
**** done Duolingo
**** done Mobility
*** Evening
**** Typing
**** Reflection
**** Mobility
** Read
*** Bible 
**** Old Testament (Lv 7:11-9:24)
**** Psalms (33:12-23)
**** Proverbs (6:37-40)
**** New Testament (Mt 22:23-46)
*** The Divine Liturgy
**** starting page: 
**** ending page  : 
**** summarization: 
** Extra
** Plan [/]
- [ ] 
- [ ] Typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |     |     |     |
