#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-05 Fri> 6:00
* Routine
** done Morning
*** done Prayer/Lives of the Saints/Lectionary
*** done Thanksgiving
- Awaking
- Deliverance from an evil dream
- Food to start the day 
- Remembrance of the fast
- Prayers of our Fathers
*** done Reflection
Had a wet dream, I complied with it. I'm getting stronger though, Glory be to God.

I'll get some work done but mainly it's going to be cleaning up, seeing mom, and leaving for Columbia for vespers.
*** done Mobility
*** done Duolingo
*** done Typing
| wpm | accuracy | word count |
|-----+----------+------------|
|  94 |       98 |         50 |
|  97 |       99 |         25 |
|  91 |       97 |         25 |
|  83 |       94 |         25 |
| 100 |       94 |         25 |
| 103 |      100 |         10 |
|  94 |      100 |         10 |
| 110 |      100 |         10 |
| 120 |      100 |         10 |
| 119 |      100 |         10 |
| 106 |       97 |         10 |
| 109 |      100 |         10 |
| 100 |       97 |         10 |
| 121 |      100 |         10 |
| 123 |      100 |         10 |
** Evening
*** Typing
| wpm | accuracy | word count |
|-----+----------+------------|
|     |          |            |
*** Mobility
*** Remembrance 
*** Reflection
*** Thanksgiving
* Plan [0/4]
- [ ] ciss245 review
- [ ] sdl
- [ ] calc
- [ ] physics
* done Read
** Bible 
*** Old Testament (Exodus 19-21) (~10 commandments~) 
Moses went up to Mt. Sinai after God telling him to do so. The Jews prepared for three days, without "touching their wives" and washing their clothes.

Christ came in a cloud, and trumpets were playing loudly at this glorious moment. Christ tells Moses to ascend the mountain, and to entreat the others to stay down, lest they be destroyed.

Then Christ gives Moses the 10 commandments, which the OSB mentions that these commandments were lower than what God put in our heart, for they condescend to man's weakness. The 10 commandments are for keeping the body pure, but Christ elevates this in the era of grace with commandments to keep the soul pure as well.

1. =I am the Lord your God, who brought you out of the land of Egypt, out of the house of bondage.=
   ~You shall have no other gods before Me.~

2. ~You shall not make for yourself an idol or a likeness of anything in heaven above, or in the earth beneath, or in the waters under the earth. You shall not bow down and serve them, for I, the Lord your God, am a jealous God, recompensing the sins of the fathers on the children to the third and fourth generation of those who hate Me; but showing mercy to thousands, to those who love Me and keep My commandments.~
   =Note: Israel even used images in their worship, this foreshadows the Incarnation. When icons are used in the Church, they aren't depicting the divine nature. They draw attention to the Incarnation.=
   =Note: "God is without passion, but He condescends to call Himself a jealous God to show the intensity of His love for man. Therefore, let us love Him with intensity, for this is very pleasing to Him." (Chrysostom)=
3. ~You shall not take the name of the Lord your God in vain, for the Lord will not hold him guiltless who takes His name in vain.~
4. ~Remember the Sabbath Day, to keep it holy. Six days you shall labor and do all your work, but the seventh day is the Sabbath of the Lord your God. In it you shall do no work: neither you, nor your son, your daughter, your male servant, your female servant, your cattle, nor your stranger who sojourns with you. For in six days the Lord made heaven and earth, the sea, and everything in them, and rested on the seventh day. Therefore, the Lord blessed the Sabbath Day and hallowed it.~ 
5. ~Honor your father and mother that it may be well with you, and your days may be long upon the good land the Lord your God is giving you.~
6. ~You shall not murder~
7. ~You shall not commit adultery~
8. ~You shall not steal~
9. ~You shall not bear false witness against your neighbor~
10. ~You shall not covet your neighbor's wife of his house, and neither shall you covet his field, nor his male servant, his female servant, his ox, his donkey, any of his cattle, or whatever belongs to your neighbor~

The Lord goes on more to expound on these things, bringing guidance to specific circumstances, including slaves, violence, cattle, etc.

*** Psalms (26)
This psalm typifies baptism, which will shelter His servant from the devils, and set them high upon His rock (vv.5-6)

All of these psalms are beautiful, I should get a psalter for prayer.
*** Proverbs (5:7-14)
These verses show to not give heedance to things rebellious of the Lord, for it is vain and the soul will be lost in the end.

It also shows what the ungodly will say to themselves after give away their life to others, and their existence to the merciless: "How I hated instruction / And turned my heart away from reproofs; / I did not hear the voice of my instructor and teacher, / Nor did I incline my ear; / Little by little I was in every evil / In the midst of the church and congregation."
*** New Testament (Mt 16)
The Sadducees and Pharisees start testing Christ and asked that He would show them a sign. Christ revealed their hypocrisy, for they claim to know the signs of the sky, but they're blinding themselves to the Son of God who became incarnate for all, for He exclaims, "A wicked and adulterous generation seeks after a sign, and no sign shall be given to it except the sign of the prophet Jonah" and He left thereafter.

Christ then exclaims when He's with His disciples a while later to not heed and to beware of the leaven of the Pharisees and the Sadducees. The disciples thought He said this because they had forgotten bread. Christ then assured them, bread to eat isn't what He was talking about, for a bigger problem is at hand, the salvation of our souls; so as to not heed and to beware the Pharisees doctrine as well as the Sadducees.

Christ then asked His disciples who people thought He was. They answered to Him many false things that the people then were believing, Christ turns from what the people say to what His disciples say, in which Peter confessed that He was the Christ, the Son of the living God. Christ blessed Peter with this confession, saying that on this confession He will build His Church. Like how Peter confessed, so will every member of Christ's body confess to be apart of His Church.

Christ also gives both Peter and the rest of the disciples the Keys of the Kingdom, which is a special authority and Christ expands on this saying they have the authority to bind and loose things on earth that will in turn be binded and loosed in heaven.

Christ begins to tell his disciples that He will be persecuted more and more and be brought up to be crucified and raised on the third day. He said these things clearly, but his disciples wouldn't know what He was talking about until it all came true. Even Peter denies these things will happen in which Christ responds rebuking Peter for he was mindful of the things of men and not mindful of the things of God. Christ then goes on to tell that those who follow Him shall pick up their cross, and deny themselves, for such a path full of suffering is worthy of the Kingdom of heaven.
=If anyone desires to come after Me, let him deny himself, and take up his cross, and follow Me. For whoever desires to save his life will lose it, but whoever loses his life for My sake will find it. For what profit is it to a man if he gains the whole world, and loses his own soul? Or what will a man give in exhange for his soul? For the Son of Man will come in the glory of His Father with His angels, and then He will reward each according to his works.=
** When God Is Not There
*** starting page: 31
*** ending page  : 49
*** summarization:
* Extra
