#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-06 Sat> 12:26
* log 
** Routine
*** done Morning
**** done Prayer/Lives of the Saints/Lectionary
**** done Thanksgiving
I got to say goodbye to my mom again. Thank You Lord.
Church was great, now in columbia mall on laptop. Thank You Lord.
**** done Reflection
Today's Saturday, tomorrows the Lord's day. The break went by quick.
**** done Mobility
**** done Duolingo
**** done Typing
| wpm | accuracy | word count |
|-----+----------+------------|
| 129 |      100 |         10 |
| 103 |      100 |         10 |
| 120 |      100 |         10 |
|  96 |       97 |         10 |
| 111 |      100 |         10 |
| 120 |      100 |         10 |
| 103 |      100 |         10 |
| 104 |       98 |         10 |
|  84 |       93 |         25 |
|  96 |       99 |         25 |
|  87 |       97 |         25 |
|  95 |       99 |         25 |
|  93 |       98 |         25 |
*** done Evening
**** Typing
| wpm | accuracy | word count |
|-----+----------+------------|
|  94 |       99 |         25 |
|  94 |       99 |         25 |
**** Mobility
**** Remembrance 
I get distracted while I'm at Church, and I keep failing to recognize that I'm supposed to be worshipping God, that's what I came there to do, instead, I'm worried about wordly things, not following Christ's commandments. Lord, forgive me.
**** Reflection
Today wasn't bad, Church two times in a day will always leave me happy.

Got some work done, I don't know if I'm ready for this next semester, but I'll get right into it. I just want to learn a bunch this semester just from school so I'll focus on school classes and put the extra math/cs stuff aside (will have to know SDL by the end of the semester though) until summer. 
**** Thanksgiving
Christ, thank You for these earthly gifts that You have given me. Do not deprive me of Your  heavenly Kingdom, but as You, came among Your apostles and gave them peace, come among us also and save us.
** Plan [1/1]
- [X] ciss245 review worksheet
** Read
*** Bible 
**** Old Testament (Exodus 22-24)
Exodus 22 was more laws, but Ex 23 and 24 were powerful.

Exodus 23 talked of Justice, in which even a care for enemies is shown.

Ex 22 also expounds on the Angel of the Lord, which is clearly what Moses wanted to convey. This makes it more understandable to believe the Moses was Trinitarian.

Ex 23 has Moses going up a mountain again, this time fasting for forty days/nights. Before this though, there is a powerful sequence in which Moses typifies the Orthodox Christian worship, with altars, sacrifice, etc.
**** Psalms (27)
This psalm was a lamentation to the Lord that included many exegetical interpretations of Christ in them which I find fascinating. Without this study Bible, it wouldn't be made known to me just how prevalent Christ is all throughout the Bible.
**** Proverbs (5:15-19)
This passage talks of the sanctity of marriage, very beautiful. It mentions to not share "your water" and to keep the wife of your youth for she will make you great.
**** New Testament (Mt 17)
Mt 17 started off with a theophany, specifically the Holy Transfiguration.

Then it moved to Christ healing a man's son, who was epileptic. First, Christ rebukes the man for his faithlessness, and defends his disciples in public. Then, He rebukes His disciples in private for their lack of faith as well. These 9 disciples didn't include James, John and Peter, the pillars of the faith.

Christ then again mentioned that He would be crucified, and His disciples were troubled.

To end this chapter, a temple tax has come upon Christ, wherefore He tells Peter to go and fish and the money that comes from the fish shall be given as His payment to taxes.
*** When God Is Not There
**** starting page: 49
**** ending page  : 69
**** summarization:
** Extra
