#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-07 Sun> 16:13
* log 
** Routine
*** done Morning
**** done Prayer/Lives of the Saints/Lectionary
**** done Thanksgiving
Thank You Lord, for all the things You have given me.

Fr. Michael presented me you both in the Liturgy and also in the teaching of the monastic life,
in which an abundance of monasteries have people that live to perfection and solely hope on you,
Lord. They pray for the whole world, may this prayer come to me as well Lord, that I may turn
back to You again in repentance.
**** done Reflection
Sundays are always great, but this one especially. Ana is staying for this semester before
switching colleges, the semester is about to start (in which the end of it I'll have a
vast expanse of cs and programming knowledge), and I will be baptized this year.

This year has an uncountable amount of blessings already and I pray for more to come, but
ultimately let me hope on You, Lord, such that no matter what happens, I keep the faith
and don't stray from you in ignorance, hatred, or worst of all, egoism.
**** done Mobility
**** done Duolingo
**** done Typing
| wpm | accuracy | word count |
|-----+----------+------------|
|  94 |       95 | 30s        |
|  84 |       91 | 30s        |
|  98 |       97 | 30s        |
|  98 |       98 | 30s        |
| 108 |      100 | 25         |
| 106 |       98 | 25         |
|  98 |       95 | 25         |
| 104 |       99 | 25         |
*** done Evening
**** done Typing
| wpm | accuracy | word count |
|-----+----------+------------|
| 102 |       97 |         25 |
|  85 |       97 |         25 |
|  93 |       98 |         25 |
| 114 |      100 |         25 |
|  91 |       96 |         25 |
|  93 |       99 |         25 |
|  97 |       99 |         25 |
| 102 |       97 |         25 |
**** done Mobility
**** done Remembrance 
Lord, I again keep straying my mind when worshipping You, help me to keep a better watch on that ...
**** done Reflection
Today went well, I didn't know classes would start tomorrow nor did I know that I could've moved in yesterday, but it's all starting, and I think I'm ready to get to work this semester ...
**** done Thanksgiving
Thank You Lord for this day in which You have given me. Seeing Lathon, Sam, Alex, Andrew (Anthony maybe?), Jonathen, Fr. Michael, Presvytera, etc. etc. was amazing, I have You to thank Lord. Blessed be John the Baptist, for he died for Your sake, Lord. Help me to be like him, for he is a great example of the Christian endurance, asceticism and love for Truth.
** Plan [5/5]
- [X] Get room cleaned up
- [X] eat at Dulany
- [X] go to Best Buy
- [X] go to Adri's
- [X] Read
** Read
*** Bible 
**** Old Testament (Ex 25-27)
Exodus 25 starts with the Israelites giving their first fruits to God as an offering. Then it goes on to talk about Moses making the Ark of the Covenant, the Table for the Holy Bread, and the Lampstand of Gold.

Ex 26 expounds more on the tabernacle and all of its dimensions and material.

Ex 27 starts off with the building of the altar, then mentions a Court for the Tabernacle. This chapter then ends with the Lighted Lamp.
**** Psalms (28)
This psalm is a prophecy concerning the baptism of Jesus Christ in the Jordan River, of which service I attended yesterday and still have the hymn in my mind from Liturgy today, "Lord, when You were baptized in the River Jordan, the Trinity was made manifest. For the voice of the Father bore witness unto You calling You His beloved Son. And the Holy Spirit in the form of a dove confirmed the truth of these words, "Christ our God, You have appeared unto us and enlightened the world, Glory to You."
**** Proverbs (5:20-23)
This section warns of sleeping with strange, lawless women, for they will ensnare a man. "For the ways of man are before the eyes of God, / And He keeps close watch on all his paths." - Pr 5:21
**** New Testament (Mt 18:1-20)
Christ first tells his disciples that unless they are converted to become as little children, they will by no means enter the Kingdom of Heaven. Humble yourself, and receive children, to then receive Christ.

"Little ones" include all who have childlike humility and simplicity, all who are poor in spirit.

He then condemns those that cause people to sin, "Woe to the world because of offenses! For offenses must come, but woe to that man by whom the offense comes!"

Christ then exclaims that if a body part causes one to sin, to cast off that part, for it is better to enter into the Kingdom than to keep a body part. (metaphor)

Christ then tells of how a shepherd (and any reasonable man) would go out and find the one sheep that was lost, compared to the other 99 that weren't for all are valuable in Christ's eyes, even sinners.

Christ then tells to forgive one's brother before going to the altar, and seek forgiveness in great lengths.
*** When God Is Not There
**** starting page: 69
**** ending page  : 87
**** summarization:
This chapter explained the "why" questions that we ask, and even the question that Christ asked. The answer to these whys is to not abandon them, but to keep crying out unto God and not forsaking Him, even though our foolish selves who can't comprehened the greater plan sometimes believe God has forsaken us. It sometimes seems this way though, but to actually believe it is horrific beyond measure, let us lament, but never fail to render our prayer to Christ. Lord, have mercy.
** Extra
