#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-08 Mon> 05:18
* log 
** Routine
*** done Morning
**** done Prayer/Lives of the Saints/Lectionary
**** done Thanksgiving
Thank You Lord, for this day which You have given me.
The first day of the second semester.
Your blessing upon me has already arrived and continues to arrive, and it arrives in every breath I take and every pump that my heart pumps. While these blessings remain, let me give you worthy repentance, so that while these blessings cease, I may be made worthy to come into your Kingdom.
**** done Reflection
Ear phones fell off overnight, missed my timer. Next time I will tell Siri to stop my music and wake me up or something, maybe have an alarm in queue of my music ...

This semester is about to start! I'm excited. I know what to expect from last semester but this time will be harder. Let me strive to learn and keep my chin up for the day, unceasingly thanking the Lord and showing love to my neighbor.
**** done Duolingo
**** done Typing
| wpm | accuracy | word count |
|-----+----------+------------|
|  86 |       97 |         25 |
|  93 |      100 |         25 |
|  77 |       95 |         25 |
**** Mobility
*** Evening
**** Typing
**** Mobility
**** Remembrance 
**** Reflection
**** Thanksgiving
** Plan [3/8]
- [X] do all reading in the morning
- [X] git push before leaving; make sure you have everything as well.
- [X] mark off bible plan for today after finishing
- [ ] CLASSES START
  - [ ] plan out ciss245 notes (use cs245.org!!!)
  - [ ] look ahead for calc 2  (use m204... .org !!!)
  - [ ] check out world literature and american history class
      for how difficult they'll be and other things ... 
- [ ] Audit situation
- [ ] get books for classes
- [ ] On-campus job
- [ ] mailbox
** Read
*** Bible 
**** Old Testament (Ex 28; 29)
Ex 28 is about Aaron's vestments (priestly vestments) and it ties in greatly with Orthodox vestments. 

I've never heard this so I will note it: the twelve names of Christ of which our faith are built is as follows:
- God
- Word
- Son
- Only-begotten
- Brightness
- Impress
- Mirror
- Image
- Wisdom
- Power
- Truth
- Life

Ex 28 ended off with more priestly garments. Ex 29 is of Aaron and his sons being consecrated as Priests. 
**** Psalms (29)
This is mostly a joyful psalm, giving praise to the Lord, for He has "lifted me up, / And did not let my enemies rejoice over me" Yet at times it is lamentatious. Good psalm, though. If I ever wake up in the middle of the night I want to just open up psalms and start reading.
**** Proverbs (6:1-6)
*Careless lips.*
- Save yourself from being spiritually harmed when participating with a friend in evil things.
- For this is a trap, as both of you are continually dragging each other lower.
**** New Testament (Mt 18:21-35)
Peter comes to Christ and asks how many times he should forgive his brother, "up to seven times?" He asks. Christ answered, "seventy-seven times"

The story of the man who owed an unthinkable amount to the king was taught, in which this man owed greatly, and was forgiven by the king with his repentance, but later, he lost this forgiveness because he acted harshly to a man who owed him.
*** When God Is Not There
**** starting page: 87
**** ending page  : 105
**** summarization:
This chapter was over the healing of the paralytic at the pool of Bethseda.

When Paul says that he preaches, "Christ crucified, a stumbling block to the jews and to the greeks foolishness." I somehow never fully grasp and forget sometimes that God is resurrection. He saves us from our worldly rational logic which leads only to despair in dark times. God is with us as well, He reveals Himself to us when we have the eyes to see and the ears to hear. 
** Extra
