#+title: Daily Log
#+author: Ryan Harvey
#+date: <2024-01-09 Tue> 06:49
* log 
** Routine
*** done Morning
**** done Prayer/Lives of the Saints/Lectionary
**** done Thanksgiving
- I lay down and slept, I awoke, for the Lord will help me.
- My parents who unceasingly care and support me.
- My friends who are with me and struggle with me at times.
- The Dulany workers for they feed me well and are kind to me.
- For all that have shown me Christ in His teachings or in any other way He manifested Himself.
**** done Reflection
Yesterday was stressful, I didn't think I would have no time to do anything during the day. Maybe I'm exaggerating, I will get use to it and I will have to slip in times to do things, no problem.
**** done Duolingo
**** done Mobility
*** done Evening
** Plan [9/9]
- [X] Do discussion post for engl
- [X] git push
- [X] eat
- [X] Go to HIST class
- [X] spend rest of day in pomodoro
  - [X] cs245
    - [X] chapter 1 study
      ended on pg 22
    - [X] quiz 1
    - [X] assignment 1 peek
  - [X] hist121 reading
- [X] Go see Monacell from 2-3pm to ask about that last line in sonnet 179
- [X] Audit situation
- [X] On-campus job
 Stafford Library - Library Student Assistant 
 Student Success - Student Success Ambassador 
 Computer Sciences - Student Employee
- [X] Typing
  | wpm | acc | wrd |
  |-----+-----+-----|
  |  94 |  96 |  25 |
  |  97 |  98 |  25 |
  | 109 | 100 |  25 |
  |  94 |  96 |  25 |
** Read
*** Bible 
**** Old Testament (Ex 30-32)
began with more temple crafting, then led to the Israelites worshipping a golden calf instead of their God, which Moses rebuked them for and united them once again.
**** Psalms (30:1-14)
This psalm is crying out to God for Him to be a shelter, for the author has been rejected by His people, because of his actions.
**** Proverbs (6:7-12)
This section tells the sluggard to look of the ways of the ant, that works and prepares food for the summer, or the honeybee, that works and is fruitful though they are of no strength compared to us.
**** New Testament (Mt 19)
First Christ tells of divorce and then voluntary celibacy for the Kingdom.

A man then comes to Christ and asks how shall he inherit eternal life. Christ tells him to keep the commandments, of which the man has, but to also sell all he has and follow Christ. This the man does not do and becomes sorrowful, for he is too attached and does not want to give up his earthly riches for eternal life.
*** When God Is Not There
**** starting page: 105
**** ending page  : 121
**** summarization: 
This chapter talked of death, and how we can come to consolation in the fact and how we can help someone else in that state. It brought many questions and perspectives, but nothing can solve what Christ accomplished and has shown in His Holy Orthodox Church.
** Extra
