* TODO Morning Routine [100%] [9/9]
:PROPERTIES:
DEADLINE: <2023-11-14 Tue>
:END:
- [X] Prayer/Lectionary/Lives of the Saints
- [X] Hygiene
- [X] Made bed
- [X] Mobility/Strength
  + /What did you do?/ 
    mobility of deep squats and hamstring stretches
- [X] *Morning reflection*
  + /What are your thoughts?/
    I need to get off my phone until all of my todos are done
- [X] *Morning intention*
  + /Overall focus of today?/
    Work and stay off my phone 
- [X] *Morning creativity*
  + /Feeling creative or smart?/
    Phone why you do me like this, prayer rope bout to be my new phone
- [X] Start planning today and use agenda to help
- [X] git push before leaving 
  make sure you take everything you need for the day
* TODO [#A] Today's goals [50%] [7/14]
:PROPERTIES:
DEADLINE: <2023-11-14 Tue>
:END:
- [X] Prayer rope/book
- [ ] Read/Note 10 pages or Read 20 pages of book FAILED!!! DON'T FAIL THIS!!
  - Input book(s) and all info here:
- [X] call a friend/family member
- [X] Duolingo
- [ ] Practice touch typing
- [X] create TODOs for agenda
- [X] finish then upload calc homework
- [X] do ciss240 quizzes & some a11
- [ ] ciss240 notes
- [ ] do all safeguard for the souls missed
- [ ] pygame plan
- [ ] foundations paper plan
- [X] check c-string chapter again for binary search
- [ ] tomorrow copy things not done into tomorrows daily goals
* TODO Evening Routine [100%] [8/8]
:PROPERTIES:
DEADLINE: <2023-11-14 Tue>
:END:
- [X] Make sure all daily goals are met 
- [X] Mobility/Isometrics
  + /What did you do?/
    practice a couple hours ago and practice in 8 hours, so I won't do anything
- [X] *Evening reflection*
  + /How's it all going?/
    It's not going so well, me and Ava are at boiling points and honestly I want it to be over, especially
    if she's decided that she never wants to join the Church, so that would be a deal-breaker for me

    Also, no phone until all my todos are done, it's destructive.
- [X] *Evening thanks*
  + /How've you been blessed today?/
    Going on a walk with my foundations class looking at birds was a blessing, glory be to God.
- [X] *Evening creativity*
  + /What do you want to express?/
    My God, am I drawing closer to you?

    Are my efforts genuine? Or am I straying from you?

    Am I like a child who acts nice and innocent around his grandma, but mercilessly steals
    from the cookie jar behind her back? And of course she knows everytime he does it.

    And yes that was a childish analogy, but am I disobeying you ultimately Lord?

    Do I treat you like a game? Like I have it figured out and my opposition doesn't?

    I shall close my mouth to avoid foolishness, and continue to follow your Church and its teachings.
    This is what you have established for the prideful, so that even in your Church they still have to realize
    that their pride can make their faith into a game that they have to compete and win at every day.
- [X] Hygiene
- [X] Prayer
- [X] 7:30+ hours of sleep
