* DONE Morning Routine [100%] [8/8]
:PROPERTIES:
DEADLINE: <2023-11-02 Thu>
:END:
- [X] Prayer
- [X] Hygiene
- [X] Made bed
- [X] Mobility/Strength
  + /What did you do?/
    2 x 5 slow (full-range pushups) and 10 slow (full-range) squats
- [X] *Morning reflection*
  + /What are your thoughts?/
    I woke up late today after a long night, I shouldn't worry about optimizing org mode at all, I should focus on work.
    And ultimately, I should focus on God and not get caught up in worldly work that takes me away from Him ultimately.
- [X] *Morning intention*
  + /Overall focus of today?/
    To get work done, now that I have captures set up, I can create a checkbox and have a guided list to do throughout the day.
- [X] *Morning creativity*
  + /Feeling creative or smart?/
    I felt creative writing my discussion post for foundations class on emotional intelligence:

    The presentation given by student affairs showed me that emotional intelligence is not only important to succeed in life, but also the key factor that makes us human.
What is emotional intelligence? It's the IQ of human emotions. Someone has emotional intelligence when they're able to control their emotions, recognize other emotions,
and respond accordingly to make the best out of the situation. It's not just a social skill, it's a deep psychological skill that requires experience as a human.
It was shown that EQ (emotional intelligence) is more valuable than IQ for the workforce. This makes sense, communication is key in the job market, and to communicate
effectively to where everyone understands each other and can collaborate even better is the ultimate goal for doing projects with one's coworkers.
Finally, it was shown that EQ was a distinguishing factor between humans and AI. Because though AI can solve logical problems faster than humans can even imagine,
AI will struggle understanding complex human emotions. Also, an AI's ability to empathize is impossible, because the person will know that the AI has never experienced
and could never imagine what they're going through.
All in all, emotional intelligence was shown by the Student Affairs to be valuable. If we want to strive in the workplace and life in general, we can improve this skill
that makes humans human

- [X] Start on checkbox list for today and structure agenda as needed 
* DONE Today's goals [0%] [0/5]
- [ ] Lectionary
- [ ] Lives of the Saints
- [ ] Prayer rope
  + 33
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
  + 100
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
    - [ ]
- [ ] Read/Note 10 pages or Read 20 pages of book
  + Input book(s) and all info here:
- [ ] call a friend/family member
* ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did not do great on this, need to do better and get in the habit with my org-checklist/agenda
* DONE Evening Routine [0%] [0/8]
:PROPERTIES:
DEADLINE: <2023-11-03 Fri>
:END:
- [ ] Make sure all daily goals are met 
- [ ] Mobility/Isometrics
  + /What did you do?/
- [ ] *Evening reflection*
  + /How's it all going?/
    It wasn't the best first day with all of this org stuff, I'll keep optimizing it but today was a fluke in terms of keeping up/adding to my
    todo list for the day. It's no problem, I'll get onto it eventually, mainly I just got caught up in homework the latter half of the day.
    Me and Ava aren't doing the best, it's starting to get distant and cold, I just wish we would both breakthrough and have that mutual Christian
    trust, but honestly I'm no better than her anyways.
- [ ] *Evening thanks*
  + /How've you been blessed today?/
    My friends and teammates keep me lively. Today was so much fun playing kickball with the throwers/sprint squad.
    Also God is on my priority list again, no matter how many times I let Him down or give Him up for idols, I will keep returning back to Him.
    May I reduce the amount of falls, and shorten the time to return to Him. Amen.
- [ ] *Evening creativity*
  + /What do you want to express?/
    ASCII art was fun (and my creativity for the night), now that I mention it I'm going to make a directory /ciss240/learn/proud/ to put things
    I was greatly happy with for the semester.
- [ ] Hygiene
- [ ] Prayer
- [ ] 7:30+ hours of sleep


I will now edit my capture templates to optimize more, then head to bed.

Unsuccessful day but it just reminds me even more that I need to focus and get in the habit of keeping this, because the possibilities for growth are endless.


* Safeguard of the Soul Day 2
** Concerning the Uncertainty of the Hour of Death
1) The verdict has been made, I must die, but I do not knwo when. I may die this very day, this very hour.
2) And I do not where I will die. I may die either where I sleep, or where I walk, or where I stamd, or any other place I go.
3) And I do not know how I will die. I might die while uncorrected in this or that sin. How is it that I still sin with such
   joy and fearlessness? That I still fall again and again so easily? That I do not flee every cause of sin? What kind of faith do I really have?
   - *Be resolved not to lose any time, for time is a great means for you to live virtuously and to arrange the days' tasks. That hour which you
     lose could very well be the last hour of your life. And that hour which you use well may bring about the eternal salvation of your soul.*
