* TODO Morning Routine [100%] [9/9]
:PROPERTIES:
DEADLINE: <2023-11-20 Mon>
:END:
- [X] Prayer/Lectionary/Lives of the Saints
- [X] Hygiene
- [X] Made bed
- [X] Mobility/Strength
  + /What did you do?/ 
    5 x 20 pushups, 5 x 20 nordic pushups
- [X] *Morning reflection*
  + /What are your thoughts?/
    I'm always conflicted with life, am I doing alright or bad? It either depends on my spiritual state
    or my productive state, which are usually contrasted with each other. This needs fixed, but above all
    I value my spiritual state, so that should be my main focus no matter how horrible I am at getting things
    done that need to be done, but that is what this org-mode is for, to help plan things out ahead of time so
    deadlines don't crunch in on me.
- [X] *Morning intention*
  + /Overall focus of today?/
    To get even more ciss240 notes done, but start on projects. I should do a little bit of each project/essay/homework
    for each class so I can return fresh on everything, but my main classes are going to be calc and ciss240, as these
    grades are more dire and are more crucial to my long term learning of coding/skills.
- [X] *Morning creativity*
  + /Feeling creative or smart?/
    I'm feeling smart, I plan to take notes on ciss240 and think of ideas heavily, and even sketch them out like I did yesterday.
- [X] Start planning today and use agenda to help
- [X] git push before leaving 
  make sure you take everything you need for the day
* TODO [#A] Today's goals [66%] [8/12]
:PROPERTIES:
DEADLINE: <2023-11-20 Mon>
:END:
- [X] Prayer rope/book
- [X] Read/Note 10 pages or Read 20 pages of book
  - Input book(s) and all info here:
book         : The House of the Dead
starting page: 95
ending page  : 110
study/read   : read
book         : The Orthodox Faith, Life, and Worship
starting page: 220
ending page  : 231
study/read   : study
- [X] call a friend/family member
- [X] Duolingo
- [X] Practice touch typing
- [X] create TODOs for agenda
- [X] finish ch 21 & 22 for ciss240
+- [ ] work on pygame and reschedule it on agenda
+- [ ] ^ same for foundations paper 3+
+- [ ] finish or progress on math homework+
- [X] help Laura unpack her boutique trailer @ 5
+- [ ] if all finished before 5, enjoy youtube (dyer)+
  but we are going to stray for all social media, we are not strong nor will we ever be strong enough to resist stupid temptations
  that arise in such small trivial ways from social media.

  When you click on social media ask yourself "What am I doing here? What is the purpose?" If no purpose arises when work needs to be done,
  put it down, and get back to work, it's that simple. Just a little discipline can go a long way.
* TODO Evening Routine [100%] [8/8]
:PROPERTIES:
DEADLINE: <2023-11-20 Mon>
:END:
- [X] Make sure all daily goals are met 
- [X] Mobility/Isometrics
  + /What did you do?/
    ankle isometrics and wrist isometrics
- [X] *Evening reflection*
  + /How's it all going?/
    It's going well. I got a lot of ciss240 notes done today, now I just plan to get my sleep schedule aligned as well as constantly improving
    (even if small amounts) at getting my to-do list done for the day. Sometimes I get too bent on one task I leave no time for others.
    I'll improve though, God willing.
- [X] *Evening thanks*
  + /How've you been blessed today?/
    Ava, I didn't fall into temptation though it's risky what we do. The time is coming where the big question gets asked, it's impending and I'm
    ready for it.
- [X] *Evening creativity*
  + /What do you want to express?/
    Christianity is the True Last Rebellion, as the zine Death to the World proclaims. It's the only belief system that can be followed perfectly,
    but the success rate is so minimal. Yet it's ever abundant in followers. It preaches that one must struggle, deny what the world offers and
    endure trials and temptations so that virtues may rise over vices in oneself. In Christianity's worldview (and rationally) this is the hardest
    thing one can do because it is rebellion against the fallen state of oneself. It's a denial of the flesh and an endeavor for the spirit.
    It's the most virtuous belief system, not only for the good effects on the soul, but the good effects on ones own mind. It is straightforward,
    incorruptible, untainted by men's desires to follow the wicked ways of the world and of fleshly desires. Christianity is composed of the whole Truth.
- [X] Hygiene
- [X] Prayer
- [X] 7:30+ hours of sleep



* Let's do better tomorrow, make time for everything, and finish up at a proper time to get needed sleep at a good time.
** May God bless us in our endeavor to further know Him, and strive to Him with our soul, a never ending journey. Amen.
