* TODO Morning Routine [100%] [7/7]
:PROPERTIES:
DEADLINE: <2023-11-29 Wed>
:END:
- [X] Prayer/Lectionary/Lives of the Saints
- [X] Hygiene
- [X] Made bed
- [X] Mobility/Strength
  + /What did you do?/ 
    some stretches, need to get a mobility routine going and a weekly
    strength mobility workout that covers all things, that could probably
    be done on wednesday with how my schedule is now.
- [X] *Morning reflection*
  + /What are your thoughts?/
    Sleep is super important, it just sucks that practice at such a late time is ruining that.

    Nevertheless, I will continue getting optimum sleep, and strive to get things done throughout
    the day so I can sleep as early as possible after practice.
- [X] *Morning intention*
  + /Overall focus of today?/
    To get work done, and to see if I can get people to sign a sheet that says they want to have
    Calc-based physics here in Columbia College next fall and the following spring.
- [X] *Morning creativity*
  + /Feeling creative or smart?/
    Math was amazing today. It helped me understand integrals better, like how they can be done
    with y as the variable instead of x. And how going from negative to positive numbers makes your
    answer positive, also does subtracting the functions in the right way. For example, would you find
    the height of a statue subtracting the top from the bottom? No, that would give you a negative answer,
    though the answer would be correct if it was an absolute value, you would subtract the bottom from the
    top.
* TODO [#A] Today's goals [61%] [8/13]
:PROPERTIES:
DEADLINE: <2023-11-29 Wed>
:END:
- [X] Start planning today and use agenda to help
- [X] git push before leaving 
  make sure you take everything you need for the day
- [X] Prayer rope/book
- [X] Read/Note 10 pages or Read 20 pages of book
  - Input book(s) and all info here:
book         : The House of the Dead 
starting page: 147
ending page  : 165
study/read   : read
- [ ] call a friend/family member
- [X] Duolingo
- [X] Practice touch typing
- [X] create TODOs for agenda
- [X] math hmwk
- [ ] ciss240 project
- [ ] pygame project
- [ ] mobility
- [ ] practice
* TODO Evening Routine [0%] [0/8]
:PROPERTIES:
DEADLINE: <2023-11-29 Wed>
:END:
- [ ] Make sure all daily goals are met 
- [ ] Mobility/Isometrics
  + /What did you do?/
- [ ] *Evening reflection*
  + /How's it all going?/
- [ ] *Evening thanks*
  + /How've you been blessed today?/
- [ ] *Evening creativity*
  + /What do you want to express?/
- [ ] Hygiene
- [ ] Prayer
- [ ] 7:30+ hours of sleep
* TODO Mobility
:PROPERTIES:
SCHEDULED: <2023-11-29 Wed +1w>
:END:
** Why
Need to get in a good habit of covering my body's mobility needs,
so I don't get tight and I atleast have somewhat of a base in
flexibility and strength in stretched positions, though this
shouldn't cover all of my extra training, which I'll do spontaneously
throughout the week with a kettlebell and other training tools to
really get strong in all positions, so I'm not weak in any position.
** [[https://www.youtube.com/watch?v=B0yfPmfR2pU][mobility routine]]
:PROPERTIES:
:ID:       93cc6b59-1f46-4ec0-887a-2a72ecf683fd
:END:
*** Side to side slides (high)
*** Side to side slides (low)
*** Lizard lunge to low lunge
*** Warrior 2
*** Downward dog to high plank
*** Child pose (5 breaths each side)
*** Repeat or go back as needed
