Time: <2023-11-03 Fri 10:54>
* DONE Morning Routine [87%] [7/8]
:PROPERTIES:
DEADLINE: <2023-11-03 Fri>
:END:
- [X] Prayer
- [X] Hygiene
- [ ] Made bed
- [X] Mobility/Strength
  + /What did you do?/
    Gym workout consisting of heavy jump clean shrugs with split squats then a superset
    Then onto a track workout of plyometrics, got a 50 inch box jump with no steps.
- [X] *Morning reflection*
  + /What are your thoughts?/
    Need to make my bed more routinely, it only takes a moment. Today I woke up and thought I needed to solve an equation,
    but like always, there's no equation to solve, and I have to get on with life instead of looking for an ultimate answer
    when I'm not even half awake. Also need to sleep better, keeping up with this checklist will help me do that.
- [X] *Morning intention*
  + /Overall focus of today?/
    I want to study for all of my four classes today, each in a different way, just to head into the weekend more nicely
    and get a good habit of these checklists.
- [X] *Morning creativity*
  + /Feeling creative or smart?/
    My God, I suffer for you, and then I spit on you, forgive me.
    My Lord, I toil for you, and then I squander your gifts, forgive me.
    My Savior, I give you thanks, and then I walk all over you, forgive me.
    Father, I follow in spirit, then my flesh drags me away from You, forgive me.

    Though I contradict my beliefs everyday, I will start the day full of faith and end the day full of faith, allowing small
    increases to Christ transforming me, so that my faith is built on a rock, and I will never deny Christ when I am tested.

    I shall strive and suffer for perfection in Christ. Amen.
- [X] Start on checkbox list for today and structure agenda as needed 
* DONE [#A] Today's goals [30%] [4/13]
:PROPERTIES:
DEADLINE: <2023-11-03 Fri>
:END: 
- [X] Lectionary
- [X] Lives of the Saints
- [X] Prayer rope
- [ ] Read/Note 10 pages or Read 20 pages of book
  - Input book(s) and all info here:
- [ ] call a friend/family member 
- [ ] ciss240 notes
- [ ] review python, see if assignment 7 is up
- [ ] talk a walk in nature and start foundations essay 
- [ ] do some calc homework
- [ ] study org-mode (maybe pdf files so I can do quizzes/assignments/notes in the future on org?)
- [X] see Dr. Price and talk philosophy
- [ ] create to-dos for things like scheduling out when to work on foundations essay, future upcoming events, etc. 
- [ ] do yesterdays Safegaurd of the Soul as well as todays
* TODO Foundations essay
:PROPERTIES:
:END:
* TODO Work on paper 3 (COLL133)
:PROPERTIES:
:LAST_REPEAT: [2023-11-09 Thu 00:21]
:END:
:PROPERTIES:
:END:
* TODO Track team meeting
:PROPERTIES:
SCHEDULED: <2023-11-09 Thu>
:END:

* Safeguard of the Soul Day 3
** Concering the Awareness of the Time of Death
1) If I do not die a sudden death, I might be informed of the time of my death so that I may amend my ways and have time to confess my sins.
    However, then I will only be able to confess with great difficulty on account of the burden of sickness.
2) Perhaps all my faculties will be working so that I will be able to examine my conscience; but then it will be veryt difficult to be in the
   right state of mind on account of my fear.
3) Perhaps I will have a heart so that I may make a good repentance; but then my conscience will be confused from so many sins. O my God, what shall I do?
   /Always have your soul in good order and remove every thing that disturbs your conscience. You should have a good Spiritual Father. And do not lost the
   time which God has given you so that you may once and for all truly amend your ways./
