* DONE Morning Routine [100%] [8/8]
:PROPERTIES:
DEADLINE: <2023-11-04 Sat>
:END:
- [X] Prayer/Lectionary/Lives of the Saints
- [X] Hygiene
- [X] Made bed
- [X] Mobility/Strength
  + /What did you do?/ 
    3 sets of 30 second Handstand walk-ins/outs to improve wrist, elbow, overall upper body.
- [X] *Morning reflection*
  + /What are your thoughts?/
    Org-agenda is going to be a struggle to get used to, but ultimately it will help me if
    I truly do it all, and a side effect of doing it all will also help me sleep earlier and
    get up earlier in the day to do all the things needed to do.
- [X] *Morning intention*
  + /Overall focus of today?/
    Go out and see my moms family for Grandpa Jeff's birthday. Then come back home and get
    my daily todos done, reading is one of the hardest to implement with my schedule but it's
    a need, so I'll have to struggle to get used to it. Also I definitely need to be more specific
    in my today's goals list, because if it's too ambiguous or I really don't know how long a task
    will take, it could mess up the rest of the tasks, so I can either have a set time to do something
    or I'm confident it won't take up too much time. Either way I need to make my tasks a little more
    specific.
- [X] *Morning creativity*
  + /Feeling creative or smart?/
    Feeling smart because I want to memorize psalms so I have a wide variety that I can just say throughout
    the day, whether out loud or in my head. They heal my soul, and bring me to Christ, the True God.
- [X] Start planning today
* DONE [#A] Today's goals [88%] [8/9]
:PROPERTIES:
DEADLINE: <2023-11-04 Sat>
:END:
- [X] Prayer rope/book
- [X] Read/Note 10 pages or Read 20 pages of book
  - Input book(s) and all info here:
book         : The Orthodox Faith, Life and Worship
starting page: 111
ending page  : 131 
study/read   : study

book         : Hypostatic Prayer 
starting page: 27
ending page  : 35
study/read   : study
- [X] call a friend/family member
- +[ ] finish rest of ch 17. and then do ch. 18 for ciss240 notes+
- [X] review python material for 30 minutes
- [X] finish 3.4 and start 3.5 of Calc homework
- [X] finish foundations weekly things
- [ ] +Study and take note of more org-info for 30 minutes+
- [X] go back in previous notes and do the Safeguard for the Soul for each day missed
  Let this be a testament to why you shouldn't just "miss" days when it's originally
  scheduled, I won't allow slacking off like that. Because ultimately falling off
  schedule in any sort of way carelessly is a sin of sloth, which leads to other
  and more severe sins...
- [X] Safeguard of the Soul
  Will see that something is on my agenda (that's scheduled +n times) and I will put
  it in my daily goals if it's the appropriate day, because as of now I believe repeating
  can't be marked done.

* DONE Evening Routine [87%] [7/8]
:PROPERTIES:
DEADLINE: <2023-11-04 Sat>
:END:
- [ ] +Make sure all daily goals are met+
- [X] Mobility/Isometrics
  + /What did you do?/
    1 min standing on toes followed by 15 second of split stance with plantarflexion on front leg to get fast twitch adaptations
- [X] *Evening reflection*
  + /How's it all going?/
    Not the best, things that take up my time ruin my schedule, I have to decide to put it off until later (everything else is done)
    if it's taking too long or I feel it's going to take long
- [X] *Evening thanks*
  + /How've you been blessed today?/
    My family, God was great to give me so many family members that I can share my love with, ultimately I want them to reunite with Christ
    but first I should show them my love which I can then tell that this love I share is reciprocated from the love that God gives me.
- [X] *Evening creativity*
  + /What do you want to express?/
    I think my solution to the last 3.4 problem was smart, it was a problem where finding the maximum area of something that formed a trapezoid, so I found the
    individual sides of the triangle of the trapezoid, since they all shared the same base. With this I found the angle that the problem wanted, I'm not sure if
    it's right completely which is why it's tormenting because checking my work is something I'm not sure about for this problem and I'm just afraid I did all of it for nothing.
- [X] Hygiene
- [X] Prayer
- [X] 7:30+ hours of sleep
  1-8:30
