



* TODO goals for the night:
- [X] finish laundry
- [X] ciss240 ch17 notes
  still need to do exercises on it, but I should be able to do those tomorrow and then start on the next chapter
* TODO Evening Routine [87%] [7/8]
:PROPERTIES:
DEADLINE: <2023-11-05 Sun>
:END:
- [X] Make sure all daily goals are met 
- [X] Mobility/Isometrics
  + /What did you do?/
    Just some mobility, deep squats paired with hamstring streches.
- [X] *Evening reflection*
  + /How's it all going?/
    It's not going the best, I feel like my sleep schedule is based on my roommate. And I'm scared that my week will be horrible if this is the case.
    It's also my fault for not settling things down, but in general I'm just scared that my sleep is gonna get all out of wack.
- [X] *Evening thanks*
  + /How've you been blessed today?/
    Liturgy was great today. Though it partially sucked because Fr. Michael was sick and couldn't make it but Matthew made it amazing with his continual
    hymns and the homily he gave that came from a book called "The Way of the Spirit". Afterwards, Sam made everyone chili even though he didn't get the
    email that lunch was going to be canceled! Then presbytera gave us little pendants that we could write our names on and draw so Fr. Michael could have
    something to hang up for his 25th anniversary in this parish. Lathon and I spent most of the day together, which I'm glad we could because he'll be
    leaving to Macedonia tomorrow. May God bless him with safety on his journey. He painted a portrait of me which wasn't finished but still looked amazing.
    Thank you God for today, though I complain and make bad decisions, you still care for me and give me good things, the greatest of these being continual
    life on earth that I may be able to repent and come closer to You. Amen.
- [X] *Evening creativity*
  + /What do you want to express?/
    Extra notes, but I think I'm going to sign up for an English minor. Which would be great. Getting better at journalling and understanding English and
    creative writing more will help me tremendously with what I want to do with my life, which is to read a mountain of books and be able to represent my
    thoughts on books either in a vlog or a personal collection that I could keep that I could write with org mode or something that could easily be exported
    into certain file formats. That would help me as a writer and as a person ultimately.
- [X] Hygiene
- [X] Prayer
- [ ] +7:30 hours of sleep+
