* DONE Morning Routine [100%] 
:PROPERTIES:
DEADLINE: <2023-11-06 Mon>
:END:
- [X] Prayer/Lectionary/Lives of the Saints
- [X] Hygiene
- [X] Made bed
- [X] Mobility/Strength
  + /What did you do?/ 
    Will have weights/practice in 30 minutes...
    Update:
    We cleaned, squatted, benched then went outside for a normal monday morning sort of practice
- [X] *Morning reflection*
  + /What are your thoughts?/
    I'm surprised I jumped out of bed so easily. I want to be strong in waking up and throwing off that complacent self so I can
    live for Christ with that sort of attitude, the attitude that nothing will stand between me and Christ. And that in this attitude,
    I'm taking heaven by force, as St. John Chrysostom expounds.
- [X] *Morning intention*
  + /Overall focus of today?/
    To get plenty of work done, I may hold off on my foundations essay sadly, just because I haven't found a good time to go out in nature.
    And I worry if I do it during the week I'll lose valuable study time. We'll see, if I'm motivated enough I could take 30-60m out of my
    day to go find an animal somewhere.
- [X] *Morning creativity*
  + /Feeling creative or smart?/
    Neither really, I really just wonder what kind of smartness it takes to achieve a problem like Q82 in 3.7 for Calc I. It's the problem
    about a gutter being made of a metal sheet and bended at both 1/3 ends at a certain theta. It gives the width of the gutter. I just feel
    like it can be solved in multiple ways. But today we'll ask Dr. Felts about it and maybe I'll see the light. I just worry that I'll never
    see the light on my own for practical problems like that, because it's useful to have math work in the real world as well as in theory.
    It would also just suck to see me hit a plateau in my math journey, but I doubt this is the case, I just have to do extra work and put my head
    in the books for longer to see patterns and get ideas of doing things, so I have hope.
- [X] Start planning today
* DONE [#A] Today's goals [100%] [12/12]
:PROPERTIES:
DEADLINE: <2023-11-06 Mon>
:END:
- [X] Prayer rope/book
- [X] finish six psalms after practice
- [X] Read/Note 10 pages or Read 20 pages of book
book         : Orthodox Faith, Life and Worship
starting page: 131
ending page  : 153
study/read   : study
  - Input book(s) and all info here:
- [X] call a friend/family member
- [X] Duolingo
- [X] Calc I homework
- [X] Do exercises of ch17 in ciss240 and start on next chapter
- [X] Do yesterday's Safeguard of the Soul as well as todays
- [X] +possibly go on a nature walk to start foundations essay+
- [X] figure out hyvee password and see if you work this Saturday pwd is: Rh0706044007!
- [X] Then sign up for Saturday's track volunteering accordingly
- [X] Look at 4-year plan and see if English minor is for you
  Will not do english major, nor the class next semester, I will talk with Garver more about the Calc-based physics next semester.
  Whether to hold off on applying for it in Mizzou or to apply for it in Mizzou and still be able to change back to CC if the class
  is available.
* TODO Evening Routine [75%] [6/8]
:PROPERTIES:
DEADLINE: <2023-11-06 Tue>
:END:
- [X] Make sure all daily goals are met 
- [ ] Mobility/Isometrics
  + /What did you do?/
- [X] *Evening reflection*
  + /How's it all going?/
    It's going well, I'm getting better at keeping my to-dos, and I'm excited to get even better at it. I find a new thing everyday that relates to emacs,
    even vimium, which is vim keys for chrome which I'm enjoying. I also wonder how much better I can grow with org-mode and all of these things, my workflow
    has definitely improved, and it hasn't even been a week. Aslong as I can keep it up, I should start getting things done again, this time in a manner that
    doesn't stop when I stop keeping up my streaks (because it's structured) and I won't just give up the structure (because it's enjoyable) so ultimately
    it is one of the best agenda/journal keepers for me. And I think it helps plenty of things than the easily-observable things on the surface level.
- [X] *Evening thanks*
  + /How've you been blessed today?/
    I was first blessed upon waking up, and immediately getting up, which I haven't done in a while, I'm glad I was able to do this.
    Secondly and more, I was blessed when Laura called me and invited me to come to the Mizzou basketball game with them, and we ended
    up taking Ava, which was amazing, it filled my soul and to meditate on that is to meditate on love. More importantly for future times
    (and now) I need to focus in on that moment and how I'm viewing love in that moment, and how I can portray this love that Christ has shown me.
- [ ] *Evening creativity*
  + /What do you want to express?/
    I don't feel like saying much, but math and computer science have shown me things today. So I will explain the math problem that I was struggling with in
    my morning routine. Ultimately you do find the area of the trapezoid, but to make it simple you can split it into a square and then two triangles. There's
    only one variable (theta) so there's no need for a constraint (if any its the width given). So next, you find how theta is represented as all of the variables
    in the objective function. Specifically, the height of the square and triangles is 10sin(theta) which makes sense once you draw a picture. Then the base of the
    triangle is determined by 10cos(theta) so after accounting for all of the variables and the needed amount of variables according to the problem, then you find the
    derivative of the function and find the critical numbers within the domain. With this, you will find the maximum of the function that's needed to solve the problem.
- [X] Hygiene
- [X] Prayer
- [X] 7:30+ hours of sleep
