* DONE Morning Routine [100%] [8/8]
:PROPERTIES:
DEADLINE: <2023-11-07 Tue>
:END:
- [X] Prayer/Lectionary/Lives of the Saints
- [X] Hygiene
- [X] Made bed
- [X] Mobility/Strength
  + /What did you do?/ 
    Went to the gym and did some kettlebell swinging
- [X] *Morning reflection*
  + /What are your thoughts?/
    I woke up late, kind of messed up my schedule, I should sleep early tonight no matter the circumstances.
- [X] *Morning intention*
  + /Overall focus of today?/
    Get work done, find my track outfit, and study.
- [X] *Morning creativity*
  + /Feeling creative or smart?/
    I feel less creative dropping the English minor (that I never had) but I shall continue reading and writing about what I
    read to maintain it. And to have projects to show employers I pretty much have an English minor or even better...
- [X] Start planning today
* DONE [#A] Today's goals [100%] [7/7]
:PROPERTIES:
DEADLINE: <2023-11-07 Tue>
:END:
- [X] Prayer rope/book
- [X] Read/Note 10 pages or Read 20 pages of book
  - Input book(s) and all info here:
book         : Orthodox Faith, Life and Worship
starting page: 153
ending page  : 171
study/read   : study
- [X] call a friend/family member
- [X] Duolingo
- [X] ciss240 notes
- [X] kettlebell swinging
- [X] start on assignment 10 for ciss240

* TODO Field trip for Foundations
:PROPERTIES:
SCHEDULED: <2023-11-14 Tue> 
:END:
* DONE Evening Routine [75%] [6/8]
:PROPERTIES:
DEADLINE: <2023-11-07 Tue>
:END:
- [X] Make sure all daily goals are met 
- [X] Mobility/Isometrics
  + /What did you do?/
    Deep squats paired with hamstring stretches.
- [X] *Evening reflection*
  + /How's it all going?/
    It's going well, I'm feeling that my schedule is effective, I'm doing things I want to do and I'm
    keeping up with things that the school demands of me.
- [X] *Evening thanks*
  + /How've you been blessed today?/
    I've been blessed with friends, both those that I think with and those that I workout with.
- [ ] *Evening creativity*
  + /What do you want to express?/
Bless the Lord, O my soul, bless His holy name. Bless the Lord, O my soul and forget not all His praises. Who heals all of your diseases, Who forgives all of your transgressions. Who satisfies your desire with good things, so that your youth shall be renewed like that
of the eagle. The Lord executes mercy and judgement... (need to memorize better) also wonder if I should be typing with my front four fingers instead of picking at it with the main three, I'll search it up... 
- [X] Hygiene
- [X] Prayer
- [ ] 7:30+ hours of sleep
