* Daily
** Morning
*** Prayer/Lives of the Saints/Lectionary
*** Thanksgiving
*** Reflection
*** Mobility
** Daily TODOs
*** Duolingo
*** Typing
| wpm | accuracy | word count |
*** Bible 
**** Old Testament
Started reading Exodus, already a great first 3 chapters:

1. Israel suffers in Egypt
   This chapter summarizes that after a new pharaoh, different from the pharaoh that Joseph was under,
   was ruler of the land, he began persecuting the Israelites heavily, especially by killing all male
   children as was possible. But the Israelite women wouldn't stand for this, and they kept their male
   children.
2. The Birth of Moses
   After more strict applications of killing the male babies, Moses was born and up till three months
   old he was hidden, but then sent on a river where the Pharaoh's daughter found him and realized that
   he was of the Israelites, she took him in though and even sent him back as if he was her kid to be
   fed by his mother, whom she paid to do so. Moses grows up and ends up killing a man to defend his
   Israelite brother, but the next day they turn against him for killing a man, so he flees.
3. The Burning Bush
   Moses is in a different land shepherding sheep when he notices a burning bush that is not being consumed
   by the fire. This is where Christ and His mother is typified, and a great theophany is shown to Moses with
   powerful words, "I AM the Existing One." "you shall say to the children of Isreal: I AM sent me to you"
**** Psalms
The famous Ps 21 (LXX) of which Christ quoted when on the Cross.

The first half is lamentations, and of self-reproach unto oneself.

Beautiful poetry and imagery, truly God-inspired.
**** Proverbs
The beginning of chapter 4 shows obedient thinking, v. 1-8 compares the
reader as like a son of parents, where the parents instruct the son and
the son shouldn't forsake their teachings, for the teachings will keep him,
they will embrace him, with a crown of graces and a crown of delight.
**** New Testament
Christ begins by telling the parable of the sower, where some seeds fell on
incapable ground for growth whereas others fell on good ground and yieled
a crop. The followers of Christ have a volition to be planted on good ground,
for they have Christ and the Church, where faith grows abundantly, as long as
the faithful partake of the synergy that God has provided and knocks for.

Christ then defends why He speaks in parables. He explained they aren't for
everyone to understand, because though they have ears to hear and eyes to see,
they neither hear nor see. But His parables are for the simple and innocent,
those who genuinely desire Him and have the faith of Abraham.

People are responsible for their lack of receptivity, and are unwilling to accept the
message of the parables. Christ's parables are intended to open the eyes of His hearers
to the Truth and lead them to produce the fruit of righteousness. Intellecual understanding
is not the path, but spiritual understanding.

"In opening to us the door to the Kingdom of heaven, the parables help us to love God and to know Him,
to understand and believe His grace, mercy and forgiveness, and to order our lives according to His Holy Word."

Christ then goes on to explain the parable of the sower.

He then goes on to tell another parable where a man is sleeping and the enemy messes with his crops. He tells the
sowers of his crop not to touch it until all crops have grown to fruition. This typifies the Church and each man
in the Church where man can be wrought with heresy and delusion after being spiritually apathetic (sleeping).
*** Read
**** Input book(s) and all info here:
***** Algorithms to Live By
****** starting page: 105
****** ending page  : 128
****** summarization:
This chapter was about scheduling.
** Evening
*** Reflection
*** Thanks
*** Remembrance 
*** Mobility
