#+title: ENGL-264W-OCA by Peter Monacell
#+author: Ryan Harvey
* course
** schedule
*** Week 1
**** Discussion Post
Sonnet 179 and 189

Sor Juana is a talented poet. She is able to convey the whole theme of her poems in just four lines. Yet the remaining 10 lines she is able give life to the topic with her beautiful imagery. For example, in Sonnet 179 Sor Juana writes of one who gives praise to a woman whom they adore. The narrator doesn't even think they are worthy to deem this woman's beauty within their reach, to merit such a grandeur as her, nor to yield their happiness to her, for they would regret seeing them as theirs. She does well with both abstract imagery on its own as well as tying in material things to emotions, as shown in her Sonnet 189, where the narrator laments of a woman who was very dear to those around her. The narrator in this sonnet laments that since this woman passed away, whom bestowed on the narrator a great light while she was living, that the eyes that bestowed this light shall die as well, along with the affections for her. The narrator transforms the whole world around them to lament for this woman, even the ink of the 'melancholy' pen of which the narrator is writing, they want to become like black tears for the woman. Finally, Sor Juana ends it with the ultimate, eternal human images, of death and love personified. The narrator even thought of Death to pity this woman, for they couldn't pardon her. Then Love (he), of which the narrator thinks that he wished he could have the eyes to see her, and that people only serve Love so as to weep for her now. Both sonnets convey deep messages and are able to store all possible symbols so as to translate the theme effectively. Such is the mastery that Sor Juana beheld as a poet.
**** Mon (Jan 8)
**** Wed
***** Read "The Enlightenment in Europe and the Americas" and "What Is Enlightenment?" (Vol D, pp, 91-104)
- "The Enlightenment in Europe and the Americas" takes a look at the past and decides whether we should follow what was set before us, or if we should abandon this authority, and let reason be our guiding factor. The flaw in this, in my opinion, is that reason isn't given a good account for. They have to say that humanity to justify even using reason and rationality in the first place as if they're just "givens."

- "What Is Enlightenment?" chapter is one I would critique heavily. Enlightenment thinkers wanted rationality and coherence so bad but they couldn't justify it!!! Following rationality isn't black and white. Just as wisdom isn't black and white, but it's gained through gaining and applying knowledge and making use of the divine faculty that God has given us. That is the truth. If that's not the truth I would argue that all arguments for a "rationality" are unjustified therefore baseless and arbitrary. The chapter literally admits, "In an intellectual revolution that has left a lasting mark on our world, humans started to see themselves, rather than gods or spirits, as the sole sources of experience, knowledge, and judgement." Yes, we can do these things, we were made in the image of God, but we don't just stop with ourselves. If we stop at the created, we have no guidance from the uncreated, and eventually we lose the idea of self. We retain God-given faculties even when we use these faculties for self-worship, or the worship of reason (which cannot and will never be the end all be all in human life, clearly). Then the point was made that we can just figure out things through scientific analysis. If an experiment runs a certain way, and the scientific method says that this outcome will be constant in our universe, what is in the universe that guarantees this? How can we guarantee that things are guaranteed? We just assume the sun will rise tomorrow, we just assume gravity will work; but if we don't have a basis for these things, we are running on assumptions that we haven't justified, therefore we can't claim to know them. (knowledge: a justified true belief) This chapter ended off with telling of flaws in the system, that some philosophers still deemed certain peoples of being inferior. I would argue this is because their idea of human nature was corrupt. Also, while they did turn from this inferiority idea, how are we to say what they did was "good" to turn away from it? How do we not know that logic and reason isn't something completely different? Is logic just something we all agree on for a definition thereby making it arbitrary with the spirit of the age?
***** Read "Sor Juana Ines De La Cruz, 1648-1695" (Vol. D, pp 246-248)
She accepted the faith it seems but also had a personal goal of her own. I'm not sure why she would call this a "vice", maybe that was the common understanding at the time. God willing she was in line with Christ's teaching in doing this.
***** Read Sor Juana Ines De La Cruz, Sonnets 179 and 289 (Vol D, p.265)
Sonnet 179 is about another woman's beauty, which the author deems themself unworthy to even think that her beauty is within reach. It gives a sacred component to a woman's beauty. 

Sonnet 189 is lamenting over a woman who dies that is close to Sor Juana. With beautiful imagery Sor Juana shows deep reverence and sorrow for this woman. I'm not sure what the last stanza means, it says to let "Love" (he) lament his own bitter fate ... now they will serve him only to weep for you. Very strange, indeed.
**** Fri
***** Read Sor Juana Ines De La Cruz, from "Response of the Poet to the Very Eminent Sor Filotea de la Cruz" (Vol. D, pp 248-263)
*** Week 2
**** Discussion Post
**** Mon (Jan 15)
No class
**** Wed 
***** Read "Voltaire (Francois-Marie Arouet) 1694-1778" (Vol D, pp 369-372)
***** Read Voltaire, /Candide/, chapters 1-13 (Vol. D, pp 372-392)
**** Fri
***** Read Voltaire, /Candide/, chapters 14-22 (Vol. D, pp. 392-414)
*** Week 3
**** Discussion Post
**** Mon (Jan 22)
***** Read Voltaire, /Candide/, chapters 23-30 (Vol. D, pp. 415-431)
**** Wed
***** Read "The World of Haiku" (Vol. D, pp. 679-681)
***** Read Kitamura Kigin, Introduction and /The Mountain Well/ (Vol. D, pp. 681-682)
**** Fri
***** Read Matsuo Basho (Vol. D, pp. 682-683)
***** Read Matsuo Basho, from /The Narrow Road to the Deep North/ (Vol. D, pp. 683-694)
*** Week 4
**** Discussion Post
**** Mon (Jan 29)
***** Read "An Age of Revolutions in Europe and the Americas" and "Revolutionary Contexts" (Vol E, pp. 3-17)
***** Read Jean-Jacques Dessalines, Introduction and "Liberty or Death" (Vol. E, pp. 36-38)
**** Wed
***** Read "Romantic Poets and Their Successors" (Vol. E, pp. 305-307)
***** Read Rosalia De Castro, Introduction (Vol. E, pp. 312-413)
***** Read Rosalia De Castro, "[You will say about these verses, and it's true]," "[Some say plants don't speak]", and "[The feet of Spring are on the stair] (Vol. E, pp. 415-416)
**** Fri
***** Read "At the Crossroads of Empire" (Vol. E, pp. 433-438)
***** Read "Ghalib 1797-1869" (Vol D, pp 479-84)
***** Read Ghalib, "[Now go and live in a place]," "[Be merciful and send for me],", and [Where's the foothold] (Vol. D, pp.484-485)
*** Week 5
**** Discussion Post
**** Mon (Feb 5)
in class: peer review
***** todo ENGL-264 Draft of Paper 1
:PROPERTIES:
:pagecount: 3 to 5
DEADLINE: <2024-02-05 Mon>
:END:
**** Wed
in class: work day
**** Fri
***** todo ENGL-264 Paper 1
:PROPERTIES:
:pagecount: 5
DEADLINE: <2024-02-09 Mon>
:END:
*** Week 6
**** Discussion Post
**** Mon (Feb 12)
In Class: Review for Midterm Exam
**** Wed
***** todo Midterm Exam ENGL-264
:PROPERTIES:
DEADLINE: <2024-02-14 Wed>
:END:
**** Fri
***** Read "Realism across the Globe" (Vol. D, pp. 569-573)
***** Read "Fyodor Dostoyevsky 1821-1881" (Vol. D, pp 574-578)
***** Read Dostoyevsky, /Notes from the Underground/ (Vol. D, pp. 578-587)
*** Week 7
**** Discussion Post
**** Mon (Feb 19)
***** Read Dostoyevsky, /Notes from the Underground/ (Vol. D, pp. 587-608)
**** Wed
***** Read Dostoyevsky, /Notes from the Underground/ (Vol. D, pp. 608-633)
**** Fri
***** Read Dostoyevsky, /Notes from the Underground/ (Vol. D, pp. 633-351)
*** Week 8
**** Discussion Post
**** Mon (Feb 26)
***** Read "Henrik Ibsen, 1828-1906" (Vol. D, pp. 721-724)
***** Read Ibsen, /Hedda Gabbler/, Act I (Vol. D, pp 725-743)
**** Wed
***** Read Ibsen, /Hedda Gabbler/, Act II (Vol. D, pp 743-760)
**** Fri
***** Read Ibsen, /Hedda Gabbler/, Act II and IV (Vol. D, pp 760-781)
*** Week 9
**** Discussion Post
**** Mon (Mar 4)
***** Read "Rabindranath Tagore 1861-1841" (Vol. D, pp. 863-866)
***** Read Tagore, "Punishment" (Vol. D, pp 867-873)
**** Wed
***** Read Modernity and Modernism, 1900-1945 (Vol. E, pp. 863-866)
***** Read F.T. Marinetti, Introduction and "The Foundation and Mnaifesto of Futurism" (Vol. E, pp. 662- 666) 
**** Fri
***** Read "Akutagawa Ryunosuke 1892-1927" (Vol. E, pp. 3-13)
***** Read Akutagawa Ryunosuke, "In a Bamboo Grove" (Vol. E, pp. 333-339(
*** Week 10
**** Discussion Post
**** Mon (Mar 11)
***** Read "Jorge Luis Borges 1899-1986" (Vol. E, pp. 452-455)
***** Read Borges, "The Garden of Forking Paths" (Vol. E, pp. 455-462)
**** Wed
***** Read "Zhand Ailing 1920-1955" (Vol. E pp. 524-525)
***** Read Zhang Ailing, "Sealed Off" (Vol. E, pp. 525-533)
**** Fri
***** Read "Modern Poetry" (Vol. E, pp. 535-536)
***** Read "Rainer Maria Rilke" (Vol. E, pp. 561-562)
***** Read Rilke, "Archaic Torso of Apollo", "The Panther", and "The Swan" (Vol. E, pp. 563-564)
*** Week 11
**** Discussion Post
**** Mon (Mar 18)
***** Read "Anna Akhmatova" (Vol. E, pp.586-588)
***** Read Akhmatova, "Requiem" (Vol. E, pp. 588-595)
**** Wed
***** Read "Postwar and Postcolonial Literature 1945-1968" (Vol. E, pp. 687-691) [this day's assignment continues on the next page]
***** read "Chinua Achebe 1930-2013" (Vol E. pp. 807-809)
***** read Chinua Achebe, "Chike's School Day's" (Vol. E, pp. 809-812)
**** Fri
***** Read "Naguib Mahfouz 1911-2006" (Vol. E, pp. 863-866)
***** Read Mahfouz, "Zaabalawi" (Vol. E, 866-873)
*** Week 12
**** Discussion Post
**** Mon (Apr 1)
***** Read "Contemporary World Literature" (Vol. E, pp. 875-881)
***** Read "Yehuda Amichai 1924-2000" (Vol. E, pp. 882-883)
***** Read Amichai, "If I Forget Thee, Jerusalem" "Sleep in Jerusalem" "Jerusalem" and "An Arab Shepherd is Searching ..."(Vol. E, pp. 883-886)
**** Wed
***** todo ENGL-264 Draft Paper 2 
:PROPERTIES:
:pagecount: 3 to 5
DEADLINE: <2024-04-03 Wed>
:END:
In class: peer review
**** Fri
In-class: Work Day
*** Week 13
**** Discussion Post
**** Mon (Apr 8)
***** todo ENGL-264 Paper 2
:PROPERTIES:
:pagecount: 3 to 5
DEADLINE: <2024-04-08 Mon>
:END:
**** Wed
***** Read "Wole Soyinka, born 1934" (Vol. E, pp. 948-950)
***** Read Soyinka, /Dead and the King's Horseman/, Scene One (Vol. E, pp. 950-962)
**** Fri
***** Read Soyinka, /Dead and the King's Horseman/, Scenes Two and Three (Vol. E, pp. 962-977)
*** Week 14
**** Discussion Post
**** Mon (Apr 15)
*****1. Read Soyinka, /Death and the King's Horseman/, Scenes Four and Five (Vol. E, pp. 977-997)
**** Wed
***** Read "Isabel Allenda, born 1942" (Vol. E, pp. 1133-1135)
***** Read Allenda, "And of Clay Are We Created" (Vol. E, pp. 1135-1141)
**** Fri
review for final exam
*** grading
- Essay 1 15%
- Essay 2 17.5%
- Midterm Exam 15%
- Final Exam 20%
- Reading Quizzes 10%
- Weekly Discussion Posts 10%
- In-Class Participation 7.5%
*** weekly discussion postings
- 200-350 words
- can skip 2 weeks
*** Monacell's office hours
Mon and Weds 10:05-11:05
Tues 14:00-15:00
